// Local tree types for the calculator example
// Uses parol-walker runtime types where possible

use std::convert::Infallible;

use crate::node_kind::{NonTerminalKind, TerminalKind};

// Re-export basic types from parol-walker
pub use parol_walker::{
    BuiltinTerminalKind, BuiltinTerminalVisitor, ConcreteSyntaxTree as GenericCst,
    CstBuilder as GenericCstBuilder, CstConstructError, CstFacade,
    CstNodeData as GenericCstNodeData, CstNodeId, InputSpan, NodeKind as GenericNodeKind,
    NonTerminalData, NonTerminalHandle, RecursiveView, TerminalData, TerminalHandle,
    ViewConstructionError,
};

// Type aliases for generated code
pub type CstNodeData = GenericCstNodeData<TerminalKind, NonTerminalKind>;
pub type NodeKind = GenericNodeKind<TerminalKind, NonTerminalKind>;
pub type Cst = GenericCst<TerminalKind, NonTerminalKind>;

// Implement BuiltinTerminalKind for TerminalKind (uses methods generated by parol)
impl BuiltinTerminalKind for TerminalKind {
    fn is_builtin_whitespace(&self) -> bool {
        // Call inherent method from parol-generated code
        TerminalKind::is_builtin_whitespace(self)
    }
    fn is_builtin_new_line(&self) -> bool {
        TerminalKind::is_builtin_new_line(self)
    }
    fn is_builtin_line_comment(&self) -> bool {
        TerminalKind::is_builtin_line_comment(self)
    }
    fn is_builtin_block_comment(&self) -> bool {
        TerminalKind::is_builtin_block_comment(self)
    }
}

// CstBuilder wrapper for this grammar
pub struct CstBuilder(
    GenericCstBuilder<TerminalKind, NonTerminalKind, fn(&'static str) -> NonTerminalKind>,
);

impl CstBuilder {
    pub fn new() -> Self {
        CstBuilder(GenericCstBuilder::new(
            TerminalKind::from_terminal_index,
            NonTerminalKind::from_non_terminal_name,
            NonTerminalKind::Calc,
        ))
    }

    pub fn build_tree(self) -> Cst {
        self.0.build_tree()
    }
}

impl Default for CstBuilder {
    fn default() -> Self {
        Self::new()
    }
}

// Implement TreeConstruct by delegating to the inner builder
impl<'t> parol_runtime::parser::parse_tree_type::TreeConstruct<'t> for CstBuilder {
    type Error = parol_runtime::ParolError;
    type Tree = Cst;

    fn open_non_terminal(
        &mut self,
        name: &'static str,
        size_hint: Option<usize>,
    ) -> Result<(), Self::Error> {
        self.0.open_non_terminal(name, size_hint)
    }

    fn close_non_terminal(&mut self) -> Result<(), Self::Error> {
        self.0.close_non_terminal()
    }

    fn add_token(&mut self, token: &parol_runtime::Token<'t>) -> Result<(), Self::Error> {
        self.0.add_token(token)
    }

    fn build(self) -> Result<Self::Tree, Self::Error> {
        self.0.build()
    }
}

// Extension methods for Cst
pub trait CstExt {
    fn root_handle(&self) -> crate::nodes::CalcHandle;
}

impl CstExt for Cst {
    fn root_handle(&self) -> crate::nodes::CalcHandle {
        crate::nodes::CalcHandle(self.root())
    }
}

// Dummy visitor for default implementations - ignores all builtin terminals
struct DummyTerminalVisitor;

// Implement BuiltinTerminalVisitor for DummyTerminalVisitor
impl<F: CstFacade<TerminalKind, NonTerminalKind>>
    BuiltinTerminalVisitor<TerminalKind, NonTerminalKind, Infallible, F> for DummyTerminalVisitor
{
    fn visit_builtin_new_line_terminal(
        &mut self,
        _terminal: CstNodeId,
        _data: TerminalData,
        _tree: &F,
    ) -> Result<(), Infallible> {
        Ok(())
    }

    fn visit_builtin_whitespace_terminal(
        &mut self,
        _terminal: CstNodeId,
        _data: TerminalData,
        _tree: &F,
    ) -> Result<(), Infallible> {
        Ok(())
    }

    fn visit_builtin_line_comment_terminal(
        &mut self,
        _terminal: CstNodeId,
        _data: TerminalData,
        _tree: &F,
    ) -> Result<(), Infallible> {
        Ok(())
    }

    fn visit_builtin_block_comment_terminal(
        &mut self,
        _terminal: CstNodeId,
        _data: TerminalData,
        _tree: &F,
    ) -> Result<(), Infallible> {
        Ok(())
    }
}

/// Convert CstConstructError<Infallible> to CstConstructError<ViewConstructionError>
/// This is safe because Infallible can never be constructed.
fn convert_error<T>(
    result: Result<T, CstConstructError<Infallible>>,
) -> Result<T, CstConstructError> {
    result.map_err(|e| match e {
        CstConstructError::ViewConstruction(ve) => CstConstructError::ViewConstruction(ve),
        CstConstructError::Visitor(inf) => match inf {},
    })
}

// Helper trait for NonTerminalHandle default implementations without visitor
pub trait NonTerminalHandleExt<T, Nt>: NonTerminalHandle<T, Nt>
where
    Self: Sized,
{
    fn new<F: CstFacade<T, Nt>>(index: CstNodeId, tree: &F) -> Result<Self, CstConstructError>
    where
        T: BuiltinTerminalKind;
    fn get_view<C: CstFacade<T, Nt>>(&self, tree: &C) -> Result<Self::View, CstConstructError>
    where
        T: BuiltinTerminalKind;
}

impl<H: NonTerminalHandle<TerminalKind, NonTerminalKind>>
    NonTerminalHandleExt<TerminalKind, NonTerminalKind> for H
{
    fn new<F: CstFacade<TerminalKind, NonTerminalKind>>(
        index: CstNodeId,
        tree: &F,
    ) -> Result<Self, CstConstructError>
    where
        TerminalKind: BuiltinTerminalKind,
    {
        convert_error(Self::new_with_visit(index, tree, &mut DummyTerminalVisitor))
    }

    fn get_view<C: CstFacade<TerminalKind, NonTerminalKind>>(
        &self,
        tree: &C,
    ) -> Result<Self::View, CstConstructError>
    where
        TerminalKind: BuiltinTerminalKind,
    {
        convert_error(self.get_view_with_visit(
            tree,
            |view, visit_ignored| (view, visit_ignored),
            &mut DummyTerminalVisitor,
        ))
    }
}

// Helper trait for RecursiveView default implementations
pub trait RecursiveViewExt<F: CstFacade<TerminalKind, NonTerminalKind>>:
    RecursiveView<TerminalKind, NonTerminalKind, F>
{
    fn get_all(&self, tree: &F) -> Result<Vec<Self::Item>, CstConstructError>
    where
        TerminalKind: BuiltinTerminalKind;
}

impl<
        R: RecursiveView<TerminalKind, NonTerminalKind, F>,
        F: CstFacade<TerminalKind, NonTerminalKind>,
    > RecursiveViewExt<F> for R
{
    fn get_all(&self, tree: &F) -> Result<Vec<Self::Item>, CstConstructError>
    where
        TerminalKind: BuiltinTerminalKind,
    {
        convert_error(self.get_all_with_visit(tree, &mut DummyTerminalVisitor))
    }
}
