// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use parol_runtime::{
    ParolError, ParseTree, TokenStream,
    parser::{
        LLKParser, LookaheadDFA, ParseType, Production, Trans, parse_tree_type::TreeConstruct,
    },
};
use scnr2::scanner;
use std::path::Path;

use crate::grammar::Grammar;
use crate::grammar_trait::GrammarAuto;

pub const TERMINAL_NAMES: &[&str; 64] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Hash",
    /*  6 */ "MapBind",
    /*  7 */ "Integer",
    /*  8 */ "Float",
    /*  9 */ "Inf",
    /* 10 */ "NaN",
    /* 11 */ "True",
    /* 12 */ "False",
    /* 13 */ "Null",
    /* 14 */ "Hole",
    /* 15 */ "Str",
    /* 16 */ "LitStr",
    /* 17 */ "Text",
    /* 18 */ "InlineCode1",
    /* 19 */ "LitStr3Start",
    /* 20 */ "LitStr2Start",
    /* 21 */ "LitStr1Start",
    /* 22 */ "DelimCodeStart3",
    /* 23 */ "DelimCodeStart2",
    /* 24 */ "DelimCodeStart1",
    /* 25 */ "CodeBlockStart3",
    /* 26 */ "CodeBlockStart4",
    /* 27 */ "CodeBlockStart5",
    /* 28 */ "CodeBlockStart6",
    /* 29 */ "CodeBlockEnd3",
    /* 30 */ "Backtick2",
    /* 31 */ "CodeBlockEnd4",
    /* 32 */ "Backtick3",
    /* 33 */ "CodeBlockEnd5",
    /* 34 */ "Backtick4",
    /* 35 */ "CodeBlockEnd6",
    /* 36 */ "Backtick5",
    /* 37 */ "NoBacktick",
    /* 38 */ "LitStr3End",
    /* 39 */ "LitStr2End",
    /* 40 */ "LitStr1End",
    /* 41 */ "SQuote",
    /* 42 */ "NoSQuote",
    /* 43 */ "DelimCodeEnd3",
    /* 44 */ "DelimCodeEnd2",
    /* 45 */ "DelimCodeEnd1",
    /* 46 */ "BacktickDelim",
    /* 47 */ "GrammarNewline",
    /* 48 */ "Ws",
    /* 49 */ "At",
    /* 50 */ "Ext",
    /* 51 */ "Dot",
    /* 52 */ "Begin",
    /* 53 */ "End",
    /* 54 */ "ArrayBegin",
    /* 55 */ "ArrayEnd",
    /* 56 */ "LParen",
    /* 57 */ "RParen",
    /* 58 */ "Bind",
    /* 59 */ "Comma",
    /* 60 */ "Continue",
    /* 61 */ "TextStart",
    /* 62 */ "Ident",
    /* 63 */ "Error",
];

scanner! {
    GrammarScanner {
        mode INITIAL {
            token r"\r\n|\r|\n" => 1; // "Newline"
            token r"[\s--\r\n]+" => 2; // "Whitespace"
            token r"//.*(\r\n|\r|\n)?" => 3; // "LineComment"
            token r"/\*/?([^/]|[^*]/)*\*/" => 4; // "BlockComment"
            token r"\#" => 5; // "Hash"
            token r"=>" => 6; // "MapBind"
            token r"[-+]?\d[\d_]*" => 7; // "Integer"
            token r"[-+]?\d[\d_]*\.\d*([eE][-+]?\d+)?(f32|f64)?|[-+]?\d[\d_]*[eE][-+]?\d+(f32|f64)?" => 8; // "Float"
            token r"[-+]?[Ii]nf" => 9; // "Inf"
            token r"[Nn]a[Nn]" => 10; // "NaN"
            token r"true" => 11; // "True"
            token r"false" => 12; // "False"
            token r"null" => 13; // "Null"
            token r"![\p{XID_Start}_]?[\p{XID_Continue}-]*" => 14; // "Hole"
            token r#""([^"]|\\")*""# => 15; // "Str"
            token r"'[^']*'" => 16; // "LitStr"
            token r"[a-zA-Z0-9-_]*`[^`\r\n]*`" => 18; // "InlineCode1"
            token r"<<<'" => 19; // "LitStr3Start"
            token r"<<'" => 20; // "LitStr2Start"
            token r"<'" => 21; // "LitStr1Start"
            token r"[a-zA-Z0-9-_]*<<<`" => 22; // "DelimCodeStart3"
            token r"[a-zA-Z0-9-_]*<<`" => 23; // "DelimCodeStart2"
            token r"[a-zA-Z0-9-_]*<`" => 24; // "DelimCodeStart1"
            token r"`{3}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 25; // "CodeBlockStart3"
            token r"`{4}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 26; // "CodeBlockStart4"
            token r"`{5}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 27; // "CodeBlockStart5"
            token r"`{6}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 28; // "CodeBlockStart6"
            token r"@" => 49; // "At"
            token r"\$" => 50; // "Ext"
            token r"\." => 51; // "Dot"
            token r"\{" => 52; // "Begin"
            token r"\}" => 53; // "End"
            token r"\[" => 54; // "ArrayBegin"
            token r"\]" => 55; // "ArrayEnd"
            token r"\(" => 56; // "LParen"
            token r"\)" => 57; // "RParen"
            token r"=" => 58; // "Bind"
            token r"," => 59; // "Comma"
            token r"\\" => 60; // "Continue"
            token r":" => 61; // "TextStart"
            token r"[\p{XID_Start}_][\p{XID_Continue}-]*" => 62; // "Ident"
            token r"." => 63; // "Error"
            on 19 enter InLitStr3;
            on 20 enter InLitStr2;
            on 21 enter InLitStr1;
            on 22 enter InDelimCode3;
            on 23 enter InDelimCode2;
            on 24 enter InDelimCode1;
            on 25 enter InCodeBlock3;
            on 26 enter InCodeBlock4;
            on 27 enter InCodeBlock5;
            on 28 enter InCodeBlock6;
            on 61 enter Text;
        }
        mode Text {
            token r"[^\r\n]*" => 17; // "Text"
            token r"\r\n|\r|\n" => 47; // "GrammarNewline"
            token r"[\s--\r\n]+" => 48; // "Ws"
            token r"." => 63; // "Error"
            on 17 enter INITIAL;
        }
        mode InCodeBlock3 {
            token r"`{3}" => 29; // "CodeBlockEnd3"
            token r"`{1,2}" => 30; // "Backtick2"
            token r"[^`]+" => 37; // "NoBacktick"
            token r"." => 63; // "Error"
            on 29 enter INITIAL;
        }
        mode InCodeBlock4 {
            token r"`{4}" => 31; // "CodeBlockEnd4"
            token r"`{1,3}" => 32; // "Backtick3"
            token r"[^`]+" => 37; // "NoBacktick"
            token r"." => 63; // "Error"
            on 31 enter INITIAL;
        }
        mode InCodeBlock5 {
            token r"`{5}" => 33; // "CodeBlockEnd5"
            token r"`{1,4}" => 34; // "Backtick4"
            token r"[^`]+" => 37; // "NoBacktick"
            token r"." => 63; // "Error"
            on 33 enter INITIAL;
        }
        mode InCodeBlock6 {
            token r"`{6}" => 35; // "CodeBlockEnd6"
            token r"`{1,5}" => 36; // "Backtick5"
            token r"[^`]+" => 37; // "NoBacktick"
            token r"." => 63; // "Error"
            on 35 enter INITIAL;
        }
        mode InLitStr1 {
            token r"'>" => 40; // "LitStr1End"
            token r"'" => 41; // "SQuote"
            token r"[^']+" => 42; // "NoSQuote"
            token r"." => 63; // "Error"
            on 40 enter INITIAL;
        }
        mode InLitStr2 {
            token r"'>>" => 39; // "LitStr2End"
            token r"'" => 41; // "SQuote"
            token r"[^']+" => 42; // "NoSQuote"
            token r"." => 63; // "Error"
            on 39 enter INITIAL;
        }
        mode InLitStr3 {
            token r"'>>>" => 38; // "LitStr3End"
            token r"'" => 41; // "SQuote"
            token r"[^']+" => 42; // "NoSQuote"
            token r"." => 63; // "Error"
            on 38 enter INITIAL;
        }
        mode InDelimCode1 {
            token r"[^`]+" => 37; // "NoBacktick"
            token r"`>" => 45; // "DelimCodeEnd1"
            token r"`" => 46; // "BacktickDelim"
            token r"." => 63; // "Error"
            on 45 enter INITIAL;
        }
        mode InDelimCode2 {
            token r"[^`]+" => 37; // "NoBacktick"
            token r"`>>" => 44; // "DelimCodeEnd2"
            token r"`" => 46; // "BacktickDelim"
            token r"." => 63; // "Error"
            on 44 enter INITIAL;
        }
        mode InDelimCode3 {
            token r"[^`]+" => 37; // "NoBacktick"
            token r"`>>>" => 43; // "DelimCodeEnd3"
            token r"`" => 46; // "BacktickDelim"
            token r"." => 63; // "Error"
            on 43 enter INITIAL;
        }
    }
}

const MAX_K: usize = 1;

pub const NON_TERMINALS: &[&str; 145] = &[
    /*   0 */ "Array",
    /*   1 */ "ArrayBegin",
    /*   2 */ "ArrayElements",
    /*   3 */ "ArrayElementsOpt",
    /*   4 */ "ArrayElementsTail",
    /*   5 */ "ArrayElementsTailOpt",
    /*   6 */ "ArrayEnd",
    /*   7 */ "ArrayMarker",
    /*   8 */ "ArrayMarkerOpt",
    /*   9 */ "ArrayOpt",
    /*  10 */ "At",
    /*  11 */ "Backtick2",
    /*  12 */ "Backtick3",
    /*  13 */ "Backtick4",
    /*  14 */ "Backtick5",
    /*  15 */ "BacktickDelim",
    /*  16 */ "Begin",
    /*  17 */ "Bind",
    /*  18 */ "Binding",
    /*  19 */ "BindingRhs",
    /*  20 */ "Boolean",
    /*  21 */ "CodeBlock",
    /*  22 */ "CodeBlock3",
    /*  23 */ "CodeBlock3List",
    /*  24 */ "CodeBlock3ListGroup",
    /*  25 */ "CodeBlock4",
    /*  26 */ "CodeBlock4List",
    /*  27 */ "CodeBlock4ListGroup",
    /*  28 */ "CodeBlock5",
    /*  29 */ "CodeBlock5List",
    /*  30 */ "CodeBlock5ListGroup",
    /*  31 */ "CodeBlock6",
    /*  32 */ "CodeBlock6List",
    /*  33 */ "CodeBlock6ListGroup",
    /*  34 */ "CodeBlockEnd3",
    /*  35 */ "CodeBlockEnd4",
    /*  36 */ "CodeBlockEnd5",
    /*  37 */ "CodeBlockEnd6",
    /*  38 */ "CodeBlockStart3",
    /*  39 */ "CodeBlockStart4",
    /*  40 */ "CodeBlockStart5",
    /*  41 */ "CodeBlockStart6",
    /*  42 */ "Comma",
    /*  43 */ "Continue",
    /*  44 */ "DelimCode",
    /*  45 */ "DelimCode1",
    /*  46 */ "DelimCode1List",
    /*  47 */ "DelimCode1ListGroup",
    /*  48 */ "DelimCode2",
    /*  49 */ "DelimCode2List",
    /*  50 */ "DelimCode2ListGroup",
    /*  51 */ "DelimCode3",
    /*  52 */ "DelimCode3List",
    /*  53 */ "DelimCode3ListGroup",
    /*  54 */ "DelimCodeEnd1",
    /*  55 */ "DelimCodeEnd2",
    /*  56 */ "DelimCodeEnd3",
    /*  57 */ "DelimCodeStart1",
    /*  58 */ "DelimCodeStart2",
    /*  59 */ "DelimCodeStart3",
    /*  60 */ "Dot",
    /*  61 */ "End",
    /*  62 */ "Eure",
    /*  63 */ "EureList",
    /*  64 */ "EureList0",
    /*  65 */ "EureOpt",
    /*  66 */ "Ext",
    /*  67 */ "ExtensionNameSpace",
    /*  68 */ "False",
    /*  69 */ "Float",
    /*  70 */ "GrammarNewline",
    /*  71 */ "Hole",
    /*  72 */ "Ident",
    /*  73 */ "Inf",
    /*  74 */ "InlineCode",
    /*  75 */ "InlineCode1",
    /*  76 */ "Integer",
    /*  77 */ "Key",
    /*  78 */ "KeyBase",
    /*  79 */ "KeyIdent",
    /*  80 */ "KeyOpt",
    /*  81 */ "KeyTuple",
    /*  82 */ "KeyTupleElements",
    /*  83 */ "KeyTupleElementsOpt",
    /*  84 */ "KeyTupleElementsTail",
    /*  85 */ "KeyTupleElementsTailOpt",
    /*  86 */ "KeyTupleOpt",
    /*  87 */ "KeyValue",
    /*  88 */ "Keys",
    /*  89 */ "KeysList",
    /*  90 */ "LParen",
    /*  91 */ "LitStr",
    /*  92 */ "LitStr1",
    /*  93 */ "LitStr1End",
    /*  94 */ "LitStr1List",
    /*  95 */ "LitStr1ListGroup",
    /*  96 */ "LitStr1Start",
    /*  97 */ "LitStr2",
    /*  98 */ "LitStr2End",
    /*  99 */ "LitStr2List",
    /* 100 */ "LitStr2ListGroup",
    /* 101 */ "LitStr2Start",
    /* 102 */ "LitStr3",
    /* 103 */ "LitStr3End",
    /* 104 */ "LitStr3List",
    /* 105 */ "LitStr3ListGroup",
    /* 106 */ "LitStr3Start",
    /* 107 */ "MapBind",
    /* 108 */ "NaN",
    /* 109 */ "NoBacktick",
    /* 110 */ "NoSQuote",
    /* 111 */ "Null",
    /* 112 */ "Number",
    /* 113 */ "Object",
    /* 114 */ "ObjectList",
    /* 115 */ "ObjectOpt",
    /* 116 */ "ObjectOpt0",
    /* 117 */ "ObjectOpt1",
    /* 118 */ "RParen",
    /* 119 */ "SQuote",
    /* 120 */ "Section",
    /* 121 */ "SectionBinding",
    /* 122 */ "SectionBody",
    /* 123 */ "SectionBodyList",
    /* 124 */ "SectionBodyOpt",
    /* 125 */ "Str",
    /* 126 */ "String",
    /* 127 */ "Strings",
    /* 128 */ "StringsList",
    /* 129 */ "Text",
    /* 130 */ "TextBinding",
    /* 131 */ "TextBindingOpt",
    /* 132 */ "TextBindingOpt0",
    /* 133 */ "TextStart",
    /* 134 */ "True",
    /* 135 */ "Tuple",
    /* 136 */ "TupleElements",
    /* 137 */ "TupleElementsOpt",
    /* 138 */ "TupleElementsTail",
    /* 139 */ "TupleElementsTailOpt",
    /* 140 */ "TupleIndex",
    /* 141 */ "TupleOpt",
    /* 142 */ "Value",
    /* 143 */ "ValueBinding",
    /* 144 */ "Ws",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 145] = &[
    /* 0 - "Array" */
    LookaheadDFA {
        prod0: 79,
        transitions: &[],
        k: 0,
    },
    /* 1 - "ArrayBegin" */
    LookaheadDFA {
        prod0: 217,
        transitions: &[],
        k: 0,
    },
    /* 2 - "ArrayElements" */
    LookaheadDFA {
        prod0: 82,
        transitions: &[],
        k: 0,
    },
    /* 3 - "ArrayElementsOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 55, 2, 84), Trans(0, 59, 1, 83)],
        k: 1,
    },
    /* 4 - "ArrayElementsTail" */
    LookaheadDFA {
        prod0: 85,
        transitions: &[],
        k: 0,
    },
    /* 5 - "ArrayElementsTailOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 86),
            Trans(0, 8, 1, 86),
            Trans(0, 9, 1, 86),
            Trans(0, 10, 1, 86),
            Trans(0, 11, 1, 86),
            Trans(0, 12, 1, 86),
            Trans(0, 13, 1, 86),
            Trans(0, 14, 1, 86),
            Trans(0, 15, 1, 86),
            Trans(0, 16, 1, 86),
            Trans(0, 18, 1, 86),
            Trans(0, 19, 1, 86),
            Trans(0, 20, 1, 86),
            Trans(0, 21, 1, 86),
            Trans(0, 22, 1, 86),
            Trans(0, 23, 1, 86),
            Trans(0, 24, 1, 86),
            Trans(0, 25, 1, 86),
            Trans(0, 26, 1, 86),
            Trans(0, 27, 1, 86),
            Trans(0, 28, 1, 86),
            Trans(0, 52, 1, 86),
            Trans(0, 54, 1, 86),
            Trans(0, 55, 2, 87),
            Trans(0, 56, 1, 86),
        ],
        k: 1,
    },
    /* 6 - "ArrayEnd" */
    LookaheadDFA {
        prod0: 218,
        transitions: &[],
        k: 0,
    },
    /* 7 - "ArrayMarker" */
    LookaheadDFA {
        prod0: 31,
        transitions: &[],
        k: 0,
    },
    /* 8 - "ArrayMarkerOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 7, 1, 32), Trans(0, 55, 2, 33)],
        k: 1,
    },
    /* 9 - "ArrayOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 80),
            Trans(0, 8, 1, 80),
            Trans(0, 9, 1, 80),
            Trans(0, 10, 1, 80),
            Trans(0, 11, 1, 80),
            Trans(0, 12, 1, 80),
            Trans(0, 13, 1, 80),
            Trans(0, 14, 1, 80),
            Trans(0, 15, 1, 80),
            Trans(0, 16, 1, 80),
            Trans(0, 18, 1, 80),
            Trans(0, 19, 1, 80),
            Trans(0, 20, 1, 80),
            Trans(0, 21, 1, 80),
            Trans(0, 22, 1, 80),
            Trans(0, 23, 1, 80),
            Trans(0, 24, 1, 80),
            Trans(0, 25, 1, 80),
            Trans(0, 26, 1, 80),
            Trans(0, 27, 1, 80),
            Trans(0, 28, 1, 80),
            Trans(0, 52, 1, 80),
            Trans(0, 54, 1, 80),
            Trans(0, 55, 2, 81),
            Trans(0, 56, 1, 80),
        ],
        k: 1,
    },
    /* 10 - "At" */
    LookaheadDFA {
        prod0: 212,
        transitions: &[],
        k: 0,
    },
    /* 11 - "Backtick2" */
    LookaheadDFA {
        prod0: 193,
        transitions: &[],
        k: 0,
    },
    /* 12 - "Backtick3" */
    LookaheadDFA {
        prod0: 195,
        transitions: &[],
        k: 0,
    },
    /* 13 - "Backtick4" */
    LookaheadDFA {
        prod0: 197,
        transitions: &[],
        k: 0,
    },
    /* 14 - "Backtick5" */
    LookaheadDFA {
        prod0: 199,
        transitions: &[],
        k: 0,
    },
    /* 15 - "BacktickDelim" */
    LookaheadDFA {
        prod0: 209,
        transitions: &[],
        k: 0,
    },
    /* 16 - "Begin" */
    LookaheadDFA {
        prod0: 215,
        transitions: &[],
        k: 0,
    },
    /* 17 - "Bind" */
    LookaheadDFA {
        prod0: 221,
        transitions: &[],
        k: 0,
    },
    /* 18 - "Binding" */
    LookaheadDFA {
        prod0: 7,
        transitions: &[],
        k: 0,
    },
    /* 19 - "BindingRhs" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 52, 2, 9), Trans(0, 58, 1, 8), Trans(0, 61, 3, 10)],
        k: 1,
    },
    /* 20 - "Boolean" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 11, 1, 105), Trans(0, 12, 2, 106)],
        k: 1,
    },
    /* 21 - "CodeBlock" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 1, 158),
            Trans(0, 26, 2, 159),
            Trans(0, 27, 3, 160),
            Trans(0, 28, 4, 161),
        ],
        k: 1,
    },
    /* 22 - "CodeBlock3" */
    LookaheadDFA {
        prod0: 162,
        transitions: &[],
        k: 0,
    },
    /* 23 - "CodeBlock3List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 29, 2, 166),
            Trans(0, 30, 1, 163),
            Trans(0, 37, 1, 163),
        ],
        k: 1,
    },
    /* 24 - "CodeBlock3ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 30, 2, 165), Trans(0, 37, 1, 164)],
        k: 1,
    },
    /* 25 - "CodeBlock4" */
    LookaheadDFA {
        prod0: 167,
        transitions: &[],
        k: 0,
    },
    /* 26 - "CodeBlock4List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 31, 2, 171),
            Trans(0, 32, 1, 168),
            Trans(0, 37, 1, 168),
        ],
        k: 1,
    },
    /* 27 - "CodeBlock4ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 32, 2, 170), Trans(0, 37, 1, 169)],
        k: 1,
    },
    /* 28 - "CodeBlock5" */
    LookaheadDFA {
        prod0: 172,
        transitions: &[],
        k: 0,
    },
    /* 29 - "CodeBlock5List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 33, 2, 176),
            Trans(0, 34, 1, 173),
            Trans(0, 37, 1, 173),
        ],
        k: 1,
    },
    /* 30 - "CodeBlock5ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 34, 2, 175), Trans(0, 37, 1, 174)],
        k: 1,
    },
    /* 31 - "CodeBlock6" */
    LookaheadDFA {
        prod0: 177,
        transitions: &[],
        k: 0,
    },
    /* 32 - "CodeBlock6List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 35, 2, 181),
            Trans(0, 36, 1, 178),
            Trans(0, 37, 1, 178),
        ],
        k: 1,
    },
    /* 33 - "CodeBlock6ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 36, 2, 180), Trans(0, 37, 1, 179)],
        k: 1,
    },
    /* 34 - "CodeBlockEnd3" */
    LookaheadDFA {
        prod0: 192,
        transitions: &[],
        k: 0,
    },
    /* 35 - "CodeBlockEnd4" */
    LookaheadDFA {
        prod0: 194,
        transitions: &[],
        k: 0,
    },
    /* 36 - "CodeBlockEnd5" */
    LookaheadDFA {
        prod0: 196,
        transitions: &[],
        k: 0,
    },
    /* 37 - "CodeBlockEnd6" */
    LookaheadDFA {
        prod0: 198,
        transitions: &[],
        k: 0,
    },
    /* 38 - "CodeBlockStart3" */
    LookaheadDFA {
        prod0: 188,
        transitions: &[],
        k: 0,
    },
    /* 39 - "CodeBlockStart4" */
    LookaheadDFA {
        prod0: 189,
        transitions: &[],
        k: 0,
    },
    /* 40 - "CodeBlockStart5" */
    LookaheadDFA {
        prod0: 190,
        transitions: &[],
        k: 0,
    },
    /* 41 - "CodeBlockStart6" */
    LookaheadDFA {
        prod0: 191,
        transitions: &[],
        k: 0,
    },
    /* 42 - "Comma" */
    LookaheadDFA {
        prod0: 222,
        transitions: &[],
        k: 0,
    },
    /* 43 - "Continue" */
    LookaheadDFA {
        prod0: 223,
        transitions: &[],
        k: 0,
    },
    /* 44 - "DelimCode" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 22, 1, 140),
            Trans(0, 23, 2, 141),
            Trans(0, 24, 3, 142),
        ],
        k: 1,
    },
    /* 45 - "DelimCode1" */
    LookaheadDFA {
        prod0: 143,
        transitions: &[],
        k: 0,
    },
    /* 46 - "DelimCode1List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 37, 1, 144),
            Trans(0, 45, 2, 147),
            Trans(0, 46, 1, 144),
        ],
        k: 1,
    },
    /* 47 - "DelimCode1ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 37, 1, 145), Trans(0, 46, 2, 146)],
        k: 1,
    },
    /* 48 - "DelimCode2" */
    LookaheadDFA {
        prod0: 148,
        transitions: &[],
        k: 0,
    },
    /* 49 - "DelimCode2List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 37, 1, 149),
            Trans(0, 44, 2, 152),
            Trans(0, 46, 1, 149),
        ],
        k: 1,
    },
    /* 50 - "DelimCode2ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 37, 1, 150), Trans(0, 46, 2, 151)],
        k: 1,
    },
    /* 51 - "DelimCode3" */
    LookaheadDFA {
        prod0: 153,
        transitions: &[],
        k: 0,
    },
    /* 52 - "DelimCode3List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 37, 1, 154),
            Trans(0, 43, 2, 157),
            Trans(0, 46, 1, 154),
        ],
        k: 1,
    },
    /* 53 - "DelimCode3ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 37, 1, 155), Trans(0, 46, 2, 156)],
        k: 1,
    },
    /* 54 - "DelimCodeEnd1" */
    LookaheadDFA {
        prod0: 208,
        transitions: &[],
        k: 0,
    },
    /* 55 - "DelimCodeEnd2" */
    LookaheadDFA {
        prod0: 207,
        transitions: &[],
        k: 0,
    },
    /* 56 - "DelimCodeEnd3" */
    LookaheadDFA {
        prod0: 206,
        transitions: &[],
        k: 0,
    },
    /* 57 - "DelimCodeStart1" */
    LookaheadDFA {
        prod0: 187,
        transitions: &[],
        k: 0,
    },
    /* 58 - "DelimCodeStart2" */
    LookaheadDFA {
        prod0: 186,
        transitions: &[],
        k: 0,
    },
    /* 59 - "DelimCodeStart3" */
    LookaheadDFA {
        prod0: 185,
        transitions: &[],
        k: 0,
    },
    /* 60 - "Dot" */
    LookaheadDFA {
        prod0: 214,
        transitions: &[],
        k: 0,
    },
    /* 61 - "End" */
    LookaheadDFA {
        prod0: 216,
        transitions: &[],
        k: 0,
    },
    /* 62 - "Eure" */
    LookaheadDFA {
        prod0: 0,
        transitions: &[],
        k: 0,
    },
    /* 63 - "EureList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 4),
            Trans(0, 5, 1, 3),
            Trans(0, 7, 1, 3),
            Trans(0, 11, 1, 3),
            Trans(0, 12, 1, 3),
            Trans(0, 13, 1, 3),
            Trans(0, 15, 1, 3),
            Trans(0, 16, 1, 3),
            Trans(0, 19, 1, 3),
            Trans(0, 20, 1, 3),
            Trans(0, 21, 1, 3),
            Trans(0, 49, 2, 4),
            Trans(0, 50, 1, 3),
            Trans(0, 53, 2, 4),
            Trans(0, 56, 1, 3),
            Trans(0, 62, 1, 3),
        ],
        k: 1,
    },
    /* 64 - "EureList0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 0, 2, 2), Trans(0, 49, 1, 1), Trans(0, 53, 2, 2)],
        k: 1,
    },
    /* 65 - "EureOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 6),
            Trans(0, 5, 2, 6),
            Trans(0, 7, 2, 6),
            Trans(0, 11, 2, 6),
            Trans(0, 12, 2, 6),
            Trans(0, 13, 2, 6),
            Trans(0, 15, 2, 6),
            Trans(0, 16, 2, 6),
            Trans(0, 19, 2, 6),
            Trans(0, 20, 2, 6),
            Trans(0, 21, 2, 6),
            Trans(0, 49, 2, 6),
            Trans(0, 50, 2, 6),
            Trans(0, 53, 2, 6),
            Trans(0, 56, 2, 6),
            Trans(0, 58, 1, 5),
            Trans(0, 62, 2, 6),
        ],
        k: 1,
    },
    /* 66 - "Ext" */
    LookaheadDFA {
        prod0: 213,
        transitions: &[],
        k: 0,
    },
    /* 67 - "ExtensionNameSpace" */
    LookaheadDFA {
        prod0: 41,
        transitions: &[],
        k: 0,
    },
    /* 68 - "False" */
    LookaheadDFA {
        prod0: 108,
        transitions: &[],
        k: 0,
    },
    /* 69 - "Float" */
    LookaheadDFA {
        prod0: 102,
        transitions: &[],
        k: 0,
    },
    /* 70 - "GrammarNewline" */
    LookaheadDFA {
        prod0: 210,
        transitions: &[],
        k: 0,
    },
    /* 71 - "Hole" */
    LookaheadDFA {
        prod0: 110,
        transitions: &[],
        k: 0,
    },
    /* 72 - "Ident" */
    LookaheadDFA {
        prod0: 225,
        transitions: &[],
        k: 0,
    },
    /* 73 - "Inf" */
    LookaheadDFA {
        prod0: 103,
        transitions: &[],
        k: 0,
    },
    /* 74 - "InlineCode" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 18, 2, 123),
            Trans(0, 22, 1, 122),
            Trans(0, 23, 1, 122),
            Trans(0, 24, 1, 122),
        ],
        k: 1,
    },
    /* 75 - "InlineCode1" */
    LookaheadDFA {
        prod0: 124,
        transitions: &[],
        k: 0,
    },
    /* 76 - "Integer" */
    LookaheadDFA {
        prod0: 101,
        transitions: &[],
        k: 0,
    },
    /* 77 - "Key" */
    LookaheadDFA {
        prod0: 28,
        transitions: &[],
        k: 0,
    },
    /* 78 - "KeyBase" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 6, 39),
            Trans(0, 7, 4, 37),
            Trans(0, 11, 1, 34),
            Trans(0, 12, 1, 34),
            Trans(0, 13, 1, 34),
            Trans(0, 15, 3, 36),
            Trans(0, 16, 3, 36),
            Trans(0, 19, 3, 36),
            Trans(0, 20, 3, 36),
            Trans(0, 21, 3, 36),
            Trans(0, 50, 2, 35),
            Trans(0, 56, 5, 38),
            Trans(0, 62, 1, 34),
        ],
        k: 1,
    },
    /* 79 - "KeyIdent" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 11, 2, 56),
            Trans(0, 12, 3, 57),
            Trans(0, 13, 4, 58),
            Trans(0, 62, 1, 55),
        ],
        k: 1,
    },
    /* 80 - "KeyOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 30),
            Trans(0, 5, 2, 30),
            Trans(0, 6, 2, 30),
            Trans(0, 7, 2, 30),
            Trans(0, 11, 2, 30),
            Trans(0, 12, 2, 30),
            Trans(0, 13, 2, 30),
            Trans(0, 15, 2, 30),
            Trans(0, 16, 2, 30),
            Trans(0, 19, 2, 30),
            Trans(0, 20, 2, 30),
            Trans(0, 21, 2, 30),
            Trans(0, 49, 2, 30),
            Trans(0, 50, 2, 30),
            Trans(0, 51, 2, 30),
            Trans(0, 52, 2, 30),
            Trans(0, 53, 2, 30),
            Trans(0, 54, 1, 29),
            Trans(0, 56, 2, 30),
            Trans(0, 58, 2, 30),
            Trans(0, 61, 2, 30),
            Trans(0, 62, 2, 30),
        ],
        k: 1,
    },
    /* 81 - "KeyTuple" */
    LookaheadDFA {
        prod0: 42,
        transitions: &[],
        k: 0,
    },
    /* 82 - "KeyTupleElements" */
    LookaheadDFA {
        prod0: 45,
        transitions: &[],
        k: 0,
    },
    /* 83 - "KeyTupleElementsOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 57, 2, 47), Trans(0, 59, 1, 46)],
        k: 1,
    },
    /* 84 - "KeyTupleElementsTail" */
    LookaheadDFA {
        prod0: 48,
        transitions: &[],
        k: 0,
    },
    /* 85 - "KeyTupleElementsTailOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 49),
            Trans(0, 11, 1, 49),
            Trans(0, 12, 1, 49),
            Trans(0, 15, 1, 49),
            Trans(0, 56, 1, 49),
            Trans(0, 57, 2, 50),
        ],
        k: 1,
    },
    /* 86 - "KeyTupleOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 43),
            Trans(0, 11, 1, 43),
            Trans(0, 12, 1, 43),
            Trans(0, 15, 1, 43),
            Trans(0, 56, 1, 43),
            Trans(0, 57, 2, 44),
        ],
        k: 1,
    },
    /* 87 - "KeyValue" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 51),
            Trans(0, 11, 2, 52),
            Trans(0, 12, 2, 52),
            Trans(0, 15, 3, 53),
            Trans(0, 56, 4, 54),
        ],
        k: 1,
    },
    /* 88 - "Keys" */
    LookaheadDFA {
        prod0: 25,
        transitions: &[],
        k: 0,
    },
    /* 89 - "KeysList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 27),
            Trans(0, 5, 2, 27),
            Trans(0, 6, 2, 27),
            Trans(0, 7, 2, 27),
            Trans(0, 11, 2, 27),
            Trans(0, 12, 2, 27),
            Trans(0, 13, 2, 27),
            Trans(0, 15, 2, 27),
            Trans(0, 16, 2, 27),
            Trans(0, 19, 2, 27),
            Trans(0, 20, 2, 27),
            Trans(0, 21, 2, 27),
            Trans(0, 49, 2, 27),
            Trans(0, 50, 2, 27),
            Trans(0, 51, 1, 26),
            Trans(0, 52, 2, 27),
            Trans(0, 53, 2, 27),
            Trans(0, 56, 2, 27),
            Trans(0, 58, 2, 27),
            Trans(0, 61, 2, 27),
            Trans(0, 62, 2, 27),
        ],
        k: 1,
    },
    /* 90 - "LParen" */
    LookaheadDFA {
        prod0: 219,
        transitions: &[],
        k: 0,
    },
    /* 91 - "LitStr" */
    LookaheadDFA {
        prod0: 120,
        transitions: &[],
        k: 0,
    },
    /* 92 - "LitStr1" */
    LookaheadDFA {
        prod0: 125,
        transitions: &[],
        k: 0,
    },
    /* 93 - "LitStr1End" */
    LookaheadDFA {
        prod0: 203,
        transitions: &[],
        k: 0,
    },
    /* 94 - "LitStr1List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 40, 2, 129),
            Trans(0, 41, 1, 126),
            Trans(0, 42, 1, 126),
        ],
        k: 1,
    },
    /* 95 - "LitStr1ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 41, 2, 128), Trans(0, 42, 1, 127)],
        k: 1,
    },
    /* 96 - "LitStr1Start" */
    LookaheadDFA {
        prod0: 184,
        transitions: &[],
        k: 0,
    },
    /* 97 - "LitStr2" */
    LookaheadDFA {
        prod0: 130,
        transitions: &[],
        k: 0,
    },
    /* 98 - "LitStr2End" */
    LookaheadDFA {
        prod0: 202,
        transitions: &[],
        k: 0,
    },
    /* 99 - "LitStr2List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 39, 2, 134),
            Trans(0, 41, 1, 131),
            Trans(0, 42, 1, 131),
        ],
        k: 1,
    },
    /* 100 - "LitStr2ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 41, 2, 133), Trans(0, 42, 1, 132)],
        k: 1,
    },
    /* 101 - "LitStr2Start" */
    LookaheadDFA {
        prod0: 183,
        transitions: &[],
        k: 0,
    },
    /* 102 - "LitStr3" */
    LookaheadDFA {
        prod0: 135,
        transitions: &[],
        k: 0,
    },
    /* 103 - "LitStr3End" */
    LookaheadDFA {
        prod0: 201,
        transitions: &[],
        k: 0,
    },
    /* 104 - "LitStr3List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 38, 2, 139),
            Trans(0, 41, 1, 136),
            Trans(0, 42, 1, 136),
        ],
        k: 1,
    },
    /* 105 - "LitStr3ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 41, 2, 138), Trans(0, 42, 1, 137)],
        k: 1,
    },
    /* 106 - "LitStr3Start" */
    LookaheadDFA {
        prod0: 182,
        transitions: &[],
        k: 0,
    },
    /* 107 - "MapBind" */
    LookaheadDFA {
        prod0: 78,
        transitions: &[],
        k: 0,
    },
    /* 108 - "NaN" */
    LookaheadDFA {
        prod0: 104,
        transitions: &[],
        k: 0,
    },
    /* 109 - "NoBacktick" */
    LookaheadDFA {
        prod0: 200,
        transitions: &[],
        k: 0,
    },
    /* 110 - "NoSQuote" */
    LookaheadDFA {
        prod0: 205,
        transitions: &[],
        k: 0,
    },
    /* 111 - "Null" */
    LookaheadDFA {
        prod0: 109,
        transitions: &[],
        k: 0,
    },
    /* 112 - "Number" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 2, 98),
            Trans(0, 8, 1, 97),
            Trans(0, 9, 3, 99),
            Trans(0, 10, 4, 100),
        ],
        k: 1,
    },
    /* 113 - "Object" */
    LookaheadDFA {
        prod0: 69,
        transitions: &[],
        k: 0,
    },
    /* 114 - "ObjectList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 1, 70),
            Trans(0, 7, 1, 70),
            Trans(0, 11, 1, 70),
            Trans(0, 12, 1, 70),
            Trans(0, 13, 1, 70),
            Trans(0, 15, 1, 70),
            Trans(0, 16, 1, 70),
            Trans(0, 19, 1, 70),
            Trans(0, 20, 1, 70),
            Trans(0, 21, 1, 70),
            Trans(0, 50, 1, 70),
            Trans(0, 53, 2, 71),
            Trans(0, 56, 1, 70),
            Trans(0, 62, 1, 70),
        ],
        k: 1,
    },
    /* 115 - "ObjectOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 77),
            Trans(0, 7, 2, 77),
            Trans(0, 11, 2, 77),
            Trans(0, 12, 2, 77),
            Trans(0, 13, 2, 77),
            Trans(0, 15, 2, 77),
            Trans(0, 16, 2, 77),
            Trans(0, 19, 2, 77),
            Trans(0, 20, 2, 77),
            Trans(0, 21, 2, 77),
            Trans(0, 50, 2, 77),
            Trans(0, 53, 2, 77),
            Trans(0, 56, 2, 77),
            Trans(0, 58, 1, 74),
            Trans(0, 62, 2, 77),
        ],
        k: 1,
    },
    /* 116 - "ObjectOpt0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 73),
            Trans(0, 7, 2, 73),
            Trans(0, 11, 2, 73),
            Trans(0, 12, 2, 73),
            Trans(0, 13, 2, 73),
            Trans(0, 15, 2, 73),
            Trans(0, 16, 2, 73),
            Trans(0, 19, 2, 73),
            Trans(0, 20, 2, 73),
            Trans(0, 21, 2, 73),
            Trans(0, 50, 2, 73),
            Trans(0, 53, 2, 73),
            Trans(0, 56, 2, 73),
            Trans(0, 59, 1, 72),
            Trans(0, 62, 2, 73),
        ],
        k: 1,
    },
    /* 117 - "ObjectOpt1" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 76),
            Trans(0, 7, 2, 76),
            Trans(0, 11, 2, 76),
            Trans(0, 12, 2, 76),
            Trans(0, 13, 2, 76),
            Trans(0, 15, 2, 76),
            Trans(0, 16, 2, 76),
            Trans(0, 19, 2, 76),
            Trans(0, 20, 2, 76),
            Trans(0, 21, 2, 76),
            Trans(0, 50, 2, 76),
            Trans(0, 53, 2, 76),
            Trans(0, 56, 2, 76),
            Trans(0, 59, 1, 75),
            Trans(0, 62, 2, 76),
        ],
        k: 1,
    },
    /* 118 - "RParen" */
    LookaheadDFA {
        prod0: 220,
        transitions: &[],
        k: 0,
    },
    /* 119 - "SQuote" */
    LookaheadDFA {
        prod0: 204,
        transitions: &[],
        k: 0,
    },
    /* 120 - "Section" */
    LookaheadDFA {
        prod0: 18,
        transitions: &[],
        k: 0,
    },
    /* 121 - "SectionBinding" */
    LookaheadDFA {
        prod0: 12,
        transitions: &[],
        k: 0,
    },
    /* 122 - "SectionBody" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 1, 19),
            Trans(0, 5, 1, 19),
            Trans(0, 7, 1, 19),
            Trans(0, 11, 1, 19),
            Trans(0, 12, 1, 19),
            Trans(0, 13, 1, 19),
            Trans(0, 15, 1, 19),
            Trans(0, 16, 1, 19),
            Trans(0, 19, 1, 19),
            Trans(0, 20, 1, 19),
            Trans(0, 21, 1, 19),
            Trans(0, 49, 1, 19),
            Trans(0, 50, 1, 19),
            Trans(0, 52, 2, 22),
            Trans(0, 53, 1, 19),
            Trans(0, 56, 1, 19),
            Trans(0, 58, 1, 19),
            Trans(0, 62, 1, 19),
        ],
        k: 1,
    },
    /* 123 - "SectionBodyList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 21),
            Trans(0, 5, 1, 20),
            Trans(0, 7, 1, 20),
            Trans(0, 11, 1, 20),
            Trans(0, 12, 1, 20),
            Trans(0, 13, 1, 20),
            Trans(0, 15, 1, 20),
            Trans(0, 16, 1, 20),
            Trans(0, 19, 1, 20),
            Trans(0, 20, 1, 20),
            Trans(0, 21, 1, 20),
            Trans(0, 49, 2, 21),
            Trans(0, 50, 1, 20),
            Trans(0, 53, 2, 21),
            Trans(0, 56, 1, 20),
            Trans(0, 62, 1, 20),
        ],
        k: 1,
    },
    /* 124 - "SectionBodyOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 24),
            Trans(0, 5, 2, 24),
            Trans(0, 7, 2, 24),
            Trans(0, 11, 2, 24),
            Trans(0, 12, 2, 24),
            Trans(0, 13, 2, 24),
            Trans(0, 15, 2, 24),
            Trans(0, 16, 2, 24),
            Trans(0, 19, 2, 24),
            Trans(0, 20, 2, 24),
            Trans(0, 21, 2, 24),
            Trans(0, 49, 2, 24),
            Trans(0, 50, 2, 24),
            Trans(0, 53, 2, 24),
            Trans(0, 56, 2, 24),
            Trans(0, 58, 1, 23),
            Trans(0, 62, 2, 24),
        ],
        k: 1,
    },
    /* 125 - "Str" */
    LookaheadDFA {
        prod0: 119,
        transitions: &[],
        k: 0,
    },
    /* 126 - "String" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 15, 1, 111),
            Trans(0, 16, 2, 112),
            Trans(0, 19, 5, 115),
            Trans(0, 20, 4, 114),
            Trans(0, 21, 3, 113),
        ],
        k: 1,
    },
    /* 127 - "Strings" */
    LookaheadDFA {
        prod0: 116,
        transitions: &[],
        k: 0,
    },
    /* 128 - "StringsList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 118),
            Trans(0, 5, 2, 118),
            Trans(0, 7, 2, 118),
            Trans(0, 11, 2, 118),
            Trans(0, 12, 2, 118),
            Trans(0, 13, 2, 118),
            Trans(0, 15, 2, 118),
            Trans(0, 16, 2, 118),
            Trans(0, 19, 2, 118),
            Trans(0, 20, 2, 118),
            Trans(0, 21, 2, 118),
            Trans(0, 49, 2, 118),
            Trans(0, 50, 2, 118),
            Trans(0, 53, 2, 118),
            Trans(0, 55, 2, 118),
            Trans(0, 56, 2, 118),
            Trans(0, 57, 2, 118),
            Trans(0, 59, 2, 118),
            Trans(0, 60, 1, 117),
            Trans(0, 62, 2, 118),
        ],
        k: 1,
    },
    /* 129 - "Text" */
    LookaheadDFA {
        prod0: 121,
        transitions: &[],
        k: 0,
    },
    /* 130 - "TextBinding" */
    LookaheadDFA {
        prod0: 13,
        transitions: &[],
        k: 0,
    },
    /* 131 - "TextBindingOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 17, 2, 17), Trans(0, 48, 1, 16)],
        k: 1,
    },
    /* 132 - "TextBindingOpt0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 15),
            Trans(0, 5, 2, 15),
            Trans(0, 7, 2, 15),
            Trans(0, 11, 2, 15),
            Trans(0, 12, 2, 15),
            Trans(0, 13, 2, 15),
            Trans(0, 15, 2, 15),
            Trans(0, 16, 2, 15),
            Trans(0, 19, 2, 15),
            Trans(0, 20, 2, 15),
            Trans(0, 21, 2, 15),
            Trans(0, 47, 1, 14),
            Trans(0, 49, 2, 15),
            Trans(0, 50, 2, 15),
            Trans(0, 53, 2, 15),
            Trans(0, 56, 2, 15),
            Trans(0, 62, 2, 15),
        ],
        k: 1,
    },
    /* 133 - "TextStart" */
    LookaheadDFA {
        prod0: 224,
        transitions: &[],
        k: 0,
    },
    /* 134 - "True" */
    LookaheadDFA {
        prod0: 107,
        transitions: &[],
        k: 0,
    },
    /* 135 - "Tuple" */
    LookaheadDFA {
        prod0: 88,
        transitions: &[],
        k: 0,
    },
    /* 136 - "TupleElements" */
    LookaheadDFA {
        prod0: 91,
        transitions: &[],
        k: 0,
    },
    /* 137 - "TupleElementsOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 57, 2, 93), Trans(0, 59, 1, 92)],
        k: 1,
    },
    /* 138 - "TupleElementsTail" */
    LookaheadDFA {
        prod0: 94,
        transitions: &[],
        k: 0,
    },
    /* 139 - "TupleElementsTailOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 95),
            Trans(0, 8, 1, 95),
            Trans(0, 9, 1, 95),
            Trans(0, 10, 1, 95),
            Trans(0, 11, 1, 95),
            Trans(0, 12, 1, 95),
            Trans(0, 13, 1, 95),
            Trans(0, 14, 1, 95),
            Trans(0, 15, 1, 95),
            Trans(0, 16, 1, 95),
            Trans(0, 18, 1, 95),
            Trans(0, 19, 1, 95),
            Trans(0, 20, 1, 95),
            Trans(0, 21, 1, 95),
            Trans(0, 22, 1, 95),
            Trans(0, 23, 1, 95),
            Trans(0, 24, 1, 95),
            Trans(0, 25, 1, 95),
            Trans(0, 26, 1, 95),
            Trans(0, 27, 1, 95),
            Trans(0, 28, 1, 95),
            Trans(0, 52, 1, 95),
            Trans(0, 54, 1, 95),
            Trans(0, 56, 1, 95),
            Trans(0, 57, 2, 96),
        ],
        k: 1,
    },
    /* 140 - "TupleIndex" */
    LookaheadDFA {
        prod0: 40,
        transitions: &[],
        k: 0,
    },
    /* 141 - "TupleOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 89),
            Trans(0, 8, 1, 89),
            Trans(0, 9, 1, 89),
            Trans(0, 10, 1, 89),
            Trans(0, 11, 1, 89),
            Trans(0, 12, 1, 89),
            Trans(0, 13, 1, 89),
            Trans(0, 14, 1, 89),
            Trans(0, 15, 1, 89),
            Trans(0, 16, 1, 89),
            Trans(0, 18, 1, 89),
            Trans(0, 19, 1, 89),
            Trans(0, 20, 1, 89),
            Trans(0, 21, 1, 89),
            Trans(0, 22, 1, 89),
            Trans(0, 23, 1, 89),
            Trans(0, 24, 1, 89),
            Trans(0, 25, 1, 89),
            Trans(0, 26, 1, 89),
            Trans(0, 27, 1, 89),
            Trans(0, 28, 1, 89),
            Trans(0, 52, 1, 89),
            Trans(0, 54, 1, 89),
            Trans(0, 56, 1, 89),
            Trans(0, 57, 2, 90),
        ],
        k: 1,
    },
    /* 142 - "Value" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 4, 62),
            Trans(0, 8, 4, 62),
            Trans(0, 9, 4, 62),
            Trans(0, 10, 4, 62),
            Trans(0, 11, 5, 63),
            Trans(0, 12, 5, 63),
            Trans(0, 13, 6, 64),
            Trans(0, 14, 8, 66),
            Trans(0, 15, 7, 65),
            Trans(0, 16, 7, 65),
            Trans(0, 18, 10, 68),
            Trans(0, 19, 7, 65),
            Trans(0, 20, 7, 65),
            Trans(0, 21, 7, 65),
            Trans(0, 22, 10, 68),
            Trans(0, 23, 10, 68),
            Trans(0, 24, 10, 68),
            Trans(0, 25, 9, 67),
            Trans(0, 26, 9, 67),
            Trans(0, 27, 9, 67),
            Trans(0, 28, 9, 67),
            Trans(0, 52, 1, 59),
            Trans(0, 54, 2, 60),
            Trans(0, 56, 3, 61),
        ],
        k: 1,
    },
    /* 143 - "ValueBinding" */
    LookaheadDFA {
        prod0: 11,
        transitions: &[],
        k: 0,
    },
    /* 144 - "Ws" */
    LookaheadDFA {
        prod0: 211,
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 226] = &[
    // 0 - Eure: EureOpt /* Option */ EureList /* Vec */ EureList0 /* Vec */;
    Production {
        lhs: 62,
        production: &[ParseType::N(64), ParseType::N(63), ParseType::N(65)],
    },
    // 1 - EureList0: Section EureList0;
    Production {
        lhs: 64,
        production: &[ParseType::N(64), ParseType::N(120)],
    },
    // 2 - EureList0: ;
    Production {
        lhs: 64,
        production: &[],
    },
    // 3 - EureList: Binding EureList;
    Production {
        lhs: 63,
        production: &[ParseType::N(63), ParseType::N(18)],
    },
    // 4 - EureList: ;
    Production {
        lhs: 63,
        production: &[],
    },
    // 5 - EureOpt: ValueBinding;
    Production {
        lhs: 65,
        production: &[ParseType::N(143)],
    },
    // 6 - EureOpt: ;
    Production {
        lhs: 65,
        production: &[],
    },
    // 7 - Binding: Keys BindingRhs;
    Production {
        lhs: 18,
        production: &[ParseType::N(19), ParseType::N(88)],
    },
    // 8 - BindingRhs: ValueBinding;
    Production {
        lhs: 19,
        production: &[ParseType::N(143)],
    },
    // 9 - BindingRhs: SectionBinding;
    Production {
        lhs: 19,
        production: &[ParseType::N(121)],
    },
    // 10 - BindingRhs: TextBinding;
    Production {
        lhs: 19,
        production: &[ParseType::N(130)],
    },
    // 11 - ValueBinding: Bind Value;
    Production {
        lhs: 143,
        production: &[ParseType::N(142), ParseType::N(17)],
    },
    // 12 - SectionBinding: Begin Eure End;
    Production {
        lhs: 121,
        production: &[ParseType::N(61), ParseType::N(62), ParseType::N(16)],
    },
    // 13 - TextBinding: TextStart TextBindingOpt /* Option */ Text TextBindingOpt0 /* Option */;
    Production {
        lhs: 130,
        production: &[
            ParseType::N(132),
            ParseType::N(129),
            ParseType::N(131),
            ParseType::N(133),
        ],
    },
    // 14 - TextBindingOpt0: GrammarNewline;
    Production {
        lhs: 132,
        production: &[ParseType::N(70)],
    },
    // 15 - TextBindingOpt0: ;
    Production {
        lhs: 132,
        production: &[],
    },
    // 16 - TextBindingOpt: Ws^ /* Clipped */;
    Production {
        lhs: 131,
        production: &[ParseType::N(144)],
    },
    // 17 - TextBindingOpt: ;
    Production {
        lhs: 131,
        production: &[],
    },
    // 18 - Section: At Keys SectionBody;
    Production {
        lhs: 120,
        production: &[ParseType::N(122), ParseType::N(88), ParseType::N(10)],
    },
    // 19 - SectionBody: SectionBodyOpt /* Option */ SectionBodyList /* Vec */;
    Production {
        lhs: 122,
        production: &[ParseType::N(123), ParseType::N(124)],
    },
    // 20 - SectionBodyList: Binding SectionBodyList;
    Production {
        lhs: 123,
        production: &[ParseType::N(123), ParseType::N(18)],
    },
    // 21 - SectionBodyList: ;
    Production {
        lhs: 123,
        production: &[],
    },
    // 22 - SectionBody: Begin Eure End;
    Production {
        lhs: 122,
        production: &[ParseType::N(61), ParseType::N(62), ParseType::N(16)],
    },
    // 23 - SectionBodyOpt: ValueBinding;
    Production {
        lhs: 124,
        production: &[ParseType::N(143)],
    },
    // 24 - SectionBodyOpt: ;
    Production {
        lhs: 124,
        production: &[],
    },
    // 25 - Keys: Key KeysList /* Vec */;
    Production {
        lhs: 88,
        production: &[ParseType::N(89), ParseType::N(77)],
    },
    // 26 - KeysList: Dot Key KeysList;
    Production {
        lhs: 89,
        production: &[ParseType::N(89), ParseType::N(77), ParseType::N(60)],
    },
    // 27 - KeysList: ;
    Production {
        lhs: 89,
        production: &[],
    },
    // 28 - Key: KeyBase KeyOpt /* Option */;
    Production {
        lhs: 77,
        production: &[ParseType::N(80), ParseType::N(78)],
    },
    // 29 - KeyOpt: ArrayMarker;
    Production {
        lhs: 80,
        production: &[ParseType::N(7)],
    },
    // 30 - KeyOpt: ;
    Production {
        lhs: 80,
        production: &[],
    },
    // 31 - ArrayMarker: ArrayBegin ArrayMarkerOpt /* Option */ ArrayEnd;
    Production {
        lhs: 7,
        production: &[ParseType::N(6), ParseType::N(8), ParseType::N(1)],
    },
    // 32 - ArrayMarkerOpt: Integer;
    Production {
        lhs: 8,
        production: &[ParseType::N(76)],
    },
    // 33 - ArrayMarkerOpt: ;
    Production {
        lhs: 8,
        production: &[],
    },
    // 34 - KeyBase: KeyIdent;
    Production {
        lhs: 78,
        production: &[ParseType::N(79)],
    },
    // 35 - KeyBase: ExtensionNameSpace;
    Production {
        lhs: 78,
        production: &[ParseType::N(67)],
    },
    // 36 - KeyBase: String;
    Production {
        lhs: 78,
        production: &[ParseType::N(126)],
    },
    // 37 - KeyBase: Integer;
    Production {
        lhs: 78,
        production: &[ParseType::N(76)],
    },
    // 38 - KeyBase: KeyTuple;
    Production {
        lhs: 78,
        production: &[ParseType::N(81)],
    },
    // 39 - KeyBase: TupleIndex;
    Production {
        lhs: 78,
        production: &[ParseType::N(140)],
    },
    // 40 - TupleIndex: '#' Integer;
    Production {
        lhs: 140,
        production: &[ParseType::N(76), ParseType::T(5)],
    },
    // 41 - ExtensionNameSpace: Ext KeyIdent;
    Production {
        lhs: 67,
        production: &[ParseType::N(79), ParseType::N(66)],
    },
    // 42 - KeyTuple: LParen KeyTupleOpt /* Option */ RParen;
    Production {
        lhs: 81,
        production: &[ParseType::N(118), ParseType::N(86), ParseType::N(90)],
    },
    // 43 - KeyTupleOpt: KeyTupleElements;
    Production {
        lhs: 86,
        production: &[ParseType::N(82)],
    },
    // 44 - KeyTupleOpt: ;
    Production {
        lhs: 86,
        production: &[],
    },
    // 45 - KeyTupleElements: KeyValue KeyTupleElementsOpt /* Option */;
    Production {
        lhs: 82,
        production: &[ParseType::N(83), ParseType::N(87)],
    },
    // 46 - KeyTupleElementsOpt: KeyTupleElementsTail;
    Production {
        lhs: 83,
        production: &[ParseType::N(84)],
    },
    // 47 - KeyTupleElementsOpt: ;
    Production {
        lhs: 83,
        production: &[],
    },
    // 48 - KeyTupleElementsTail: Comma KeyTupleElementsTailOpt /* Option */;
    Production {
        lhs: 84,
        production: &[ParseType::N(85), ParseType::N(42)],
    },
    // 49 - KeyTupleElementsTailOpt: KeyTupleElements;
    Production {
        lhs: 85,
        production: &[ParseType::N(82)],
    },
    // 50 - KeyTupleElementsTailOpt: ;
    Production {
        lhs: 85,
        production: &[],
    },
    // 51 - KeyValue: Integer;
    Production {
        lhs: 87,
        production: &[ParseType::N(76)],
    },
    // 52 - KeyValue: Boolean;
    Production {
        lhs: 87,
        production: &[ParseType::N(20)],
    },
    // 53 - KeyValue: Str;
    Production {
        lhs: 87,
        production: &[ParseType::N(125)],
    },
    // 54 - KeyValue: KeyTuple;
    Production {
        lhs: 87,
        production: &[ParseType::N(81)],
    },
    // 55 - KeyIdent: Ident;
    Production {
        lhs: 79,
        production: &[ParseType::N(72)],
    },
    // 56 - KeyIdent: True;
    Production {
        lhs: 79,
        production: &[ParseType::N(134)],
    },
    // 57 - KeyIdent: False;
    Production {
        lhs: 79,
        production: &[ParseType::N(68)],
    },
    // 58 - KeyIdent: Null;
    Production {
        lhs: 79,
        production: &[ParseType::N(111)],
    },
    // 59 - Value: Object;
    Production {
        lhs: 142,
        production: &[ParseType::N(113)],
    },
    // 60 - Value: Array;
    Production {
        lhs: 142,
        production: &[ParseType::N(0)],
    },
    // 61 - Value: Tuple;
    Production {
        lhs: 142,
        production: &[ParseType::N(135)],
    },
    // 62 - Value: Number;
    Production {
        lhs: 142,
        production: &[ParseType::N(112)],
    },
    // 63 - Value: Boolean;
    Production {
        lhs: 142,
        production: &[ParseType::N(20)],
    },
    // 64 - Value: Null;
    Production {
        lhs: 142,
        production: &[ParseType::N(111)],
    },
    // 65 - Value: Strings;
    Production {
        lhs: 142,
        production: &[ParseType::N(127)],
    },
    // 66 - Value: Hole;
    Production {
        lhs: 142,
        production: &[ParseType::N(71)],
    },
    // 67 - Value: CodeBlock;
    Production {
        lhs: 142,
        production: &[ParseType::N(21)],
    },
    // 68 - Value: InlineCode;
    Production {
        lhs: 142,
        production: &[ParseType::N(74)],
    },
    // 69 - Object: Begin ObjectOpt /* Option */ ObjectList /* Vec */ End;
    Production {
        lhs: 113,
        production: &[
            ParseType::N(61),
            ParseType::N(114),
            ParseType::N(115),
            ParseType::N(16),
        ],
    },
    // 70 - ObjectList: Keys MapBind Value ObjectOpt0 /* Option */ ObjectList;
    Production {
        lhs: 114,
        production: &[
            ParseType::N(114),
            ParseType::N(116),
            ParseType::N(142),
            ParseType::N(107),
            ParseType::N(88),
        ],
    },
    // 71 - ObjectList: ;
    Production {
        lhs: 114,
        production: &[],
    },
    // 72 - ObjectOpt0: Comma;
    Production {
        lhs: 116,
        production: &[ParseType::N(42)],
    },
    // 73 - ObjectOpt0: ;
    Production {
        lhs: 116,
        production: &[],
    },
    // 74 - ObjectOpt: ValueBinding ObjectOpt1 /* Option */;
    Production {
        lhs: 115,
        production: &[ParseType::N(117), ParseType::N(143)],
    },
    // 75 - ObjectOpt1: Comma;
    Production {
        lhs: 117,
        production: &[ParseType::N(42)],
    },
    // 76 - ObjectOpt1: ;
    Production {
        lhs: 117,
        production: &[],
    },
    // 77 - ObjectOpt: ;
    Production {
        lhs: 115,
        production: &[],
    },
    // 78 - MapBind: '=>';
    Production {
        lhs: 107,
        production: &[ParseType::T(6)],
    },
    // 79 - Array: ArrayBegin ArrayOpt /* Option */ ArrayEnd;
    Production {
        lhs: 0,
        production: &[ParseType::N(6), ParseType::N(9), ParseType::N(1)],
    },
    // 80 - ArrayOpt: ArrayElements;
    Production {
        lhs: 9,
        production: &[ParseType::N(2)],
    },
    // 81 - ArrayOpt: ;
    Production {
        lhs: 9,
        production: &[],
    },
    // 82 - ArrayElements: Value ArrayElementsOpt /* Option */;
    Production {
        lhs: 2,
        production: &[ParseType::N(3), ParseType::N(142)],
    },
    // 83 - ArrayElementsOpt: ArrayElementsTail;
    Production {
        lhs: 3,
        production: &[ParseType::N(4)],
    },
    // 84 - ArrayElementsOpt: ;
    Production {
        lhs: 3,
        production: &[],
    },
    // 85 - ArrayElementsTail: Comma ArrayElementsTailOpt /* Option */;
    Production {
        lhs: 4,
        production: &[ParseType::N(5), ParseType::N(42)],
    },
    // 86 - ArrayElementsTailOpt: ArrayElements;
    Production {
        lhs: 5,
        production: &[ParseType::N(2)],
    },
    // 87 - ArrayElementsTailOpt: ;
    Production {
        lhs: 5,
        production: &[],
    },
    // 88 - Tuple: LParen TupleOpt /* Option */ RParen;
    Production {
        lhs: 135,
        production: &[ParseType::N(118), ParseType::N(141), ParseType::N(90)],
    },
    // 89 - TupleOpt: TupleElements;
    Production {
        lhs: 141,
        production: &[ParseType::N(136)],
    },
    // 90 - TupleOpt: ;
    Production {
        lhs: 141,
        production: &[],
    },
    // 91 - TupleElements: Value TupleElementsOpt /* Option */;
    Production {
        lhs: 136,
        production: &[ParseType::N(137), ParseType::N(142)],
    },
    // 92 - TupleElementsOpt: TupleElementsTail;
    Production {
        lhs: 137,
        production: &[ParseType::N(138)],
    },
    // 93 - TupleElementsOpt: ;
    Production {
        lhs: 137,
        production: &[],
    },
    // 94 - TupleElementsTail: Comma TupleElementsTailOpt /* Option */;
    Production {
        lhs: 138,
        production: &[ParseType::N(139), ParseType::N(42)],
    },
    // 95 - TupleElementsTailOpt: TupleElements;
    Production {
        lhs: 139,
        production: &[ParseType::N(136)],
    },
    // 96 - TupleElementsTailOpt: ;
    Production {
        lhs: 139,
        production: &[],
    },
    // 97 - Number: Float;
    Production {
        lhs: 112,
        production: &[ParseType::N(69)],
    },
    // 98 - Number: Integer;
    Production {
        lhs: 112,
        production: &[ParseType::N(76)],
    },
    // 99 - Number: Inf;
    Production {
        lhs: 112,
        production: &[ParseType::N(73)],
    },
    // 100 - Number: NaN;
    Production {
        lhs: 112,
        production: &[ParseType::N(108)],
    },
    // 101 - Integer: /[-+]?\d[\d_]*/;
    Production {
        lhs: 76,
        production: &[ParseType::T(7)],
    },
    // 102 - Float: /[-+]?\d[\d_]*\.\d*([eE][-+]?\d+)?(f32|f64)?|[-+]?\d[\d_]*[eE][-+]?\d+(f32|f64)?/;
    Production {
        lhs: 69,
        production: &[ParseType::T(8)],
    },
    // 103 - Inf: /[-+]?[Ii]nf/;
    Production {
        lhs: 73,
        production: &[ParseType::T(9)],
    },
    // 104 - NaN: /[Nn]a[Nn]/;
    Production {
        lhs: 108,
        production: &[ParseType::T(10)],
    },
    // 105 - Boolean: True;
    Production {
        lhs: 20,
        production: &[ParseType::N(134)],
    },
    // 106 - Boolean: False;
    Production {
        lhs: 20,
        production: &[ParseType::N(68)],
    },
    // 107 - True: 'true';
    Production {
        lhs: 134,
        production: &[ParseType::T(11)],
    },
    // 108 - False: 'false';
    Production {
        lhs: 68,
        production: &[ParseType::T(12)],
    },
    // 109 - Null: 'null';
    Production {
        lhs: 111,
        production: &[ParseType::T(13)],
    },
    // 110 - Hole: /![\p{XID_Start}_]?[\p{XID_Continue}-]*/;
    Production {
        lhs: 71,
        production: &[ParseType::T(14)],
    },
    // 111 - String: Str;
    Production {
        lhs: 126,
        production: &[ParseType::N(125)],
    },
    // 112 - String: LitStr;
    Production {
        lhs: 126,
        production: &[ParseType::N(91)],
    },
    // 113 - String: LitStr1;
    Production {
        lhs: 126,
        production: &[ParseType::N(92)],
    },
    // 114 - String: LitStr2;
    Production {
        lhs: 126,
        production: &[ParseType::N(97)],
    },
    // 115 - String: LitStr3;
    Production {
        lhs: 126,
        production: &[ParseType::N(102)],
    },
    // 116 - Strings: String StringsList /* Vec */;
    Production {
        lhs: 127,
        production: &[ParseType::N(128), ParseType::N(126)],
    },
    // 117 - StringsList: Continue String StringsList;
    Production {
        lhs: 128,
        production: &[ParseType::N(128), ParseType::N(126), ParseType::N(43)],
    },
    // 118 - StringsList: ;
    Production {
        lhs: 128,
        production: &[],
    },
    // 119 - Str: /"([^"]|\\")*"/;
    Production {
        lhs: 125,
        production: &[ParseType::T(15)],
    },
    // 120 - LitStr: /'[^']*'/;
    Production {
        lhs: 91,
        production: &[ParseType::T(16)],
    },
    // 121 - Text: /[^\r\n]*/;
    Production {
        lhs: 129,
        production: &[ParseType::T(17)],
    },
    // 122 - InlineCode: DelimCode;
    Production {
        lhs: 74,
        production: &[ParseType::N(44)],
    },
    // 123 - InlineCode: InlineCode1;
    Production {
        lhs: 74,
        production: &[ParseType::N(75)],
    },
    // 124 - InlineCode1: /[a-zA-Z0-9-_]*`[^`\r\n]*`/;
    Production {
        lhs: 75,
        production: &[ParseType::T(18)],
    },
    // 125 - LitStr1: LitStr1Start LitStr1List /* Vec */ LitStr1End;
    Production {
        lhs: 92,
        production: &[ParseType::N(93), ParseType::N(94), ParseType::N(96)],
    },
    // 126 - LitStr1List: LitStr1ListGroup LitStr1List;
    Production {
        lhs: 94,
        production: &[ParseType::N(94), ParseType::N(95)],
    },
    // 127 - LitStr1ListGroup: NoSQuote;
    Production {
        lhs: 95,
        production: &[ParseType::N(110)],
    },
    // 128 - LitStr1ListGroup: SQuote;
    Production {
        lhs: 95,
        production: &[ParseType::N(119)],
    },
    // 129 - LitStr1List: ;
    Production {
        lhs: 94,
        production: &[],
    },
    // 130 - LitStr2: LitStr2Start LitStr2List /* Vec */ LitStr2End;
    Production {
        lhs: 97,
        production: &[ParseType::N(98), ParseType::N(99), ParseType::N(101)],
    },
    // 131 - LitStr2List: LitStr2ListGroup LitStr2List;
    Production {
        lhs: 99,
        production: &[ParseType::N(99), ParseType::N(100)],
    },
    // 132 - LitStr2ListGroup: NoSQuote;
    Production {
        lhs: 100,
        production: &[ParseType::N(110)],
    },
    // 133 - LitStr2ListGroup: SQuote;
    Production {
        lhs: 100,
        production: &[ParseType::N(119)],
    },
    // 134 - LitStr2List: ;
    Production {
        lhs: 99,
        production: &[],
    },
    // 135 - LitStr3: LitStr3Start LitStr3List /* Vec */ LitStr3End;
    Production {
        lhs: 102,
        production: &[ParseType::N(103), ParseType::N(104), ParseType::N(106)],
    },
    // 136 - LitStr3List: LitStr3ListGroup LitStr3List;
    Production {
        lhs: 104,
        production: &[ParseType::N(104), ParseType::N(105)],
    },
    // 137 - LitStr3ListGroup: NoSQuote;
    Production {
        lhs: 105,
        production: &[ParseType::N(110)],
    },
    // 138 - LitStr3ListGroup: SQuote;
    Production {
        lhs: 105,
        production: &[ParseType::N(119)],
    },
    // 139 - LitStr3List: ;
    Production {
        lhs: 104,
        production: &[],
    },
    // 140 - DelimCode: DelimCode3;
    Production {
        lhs: 44,
        production: &[ParseType::N(51)],
    },
    // 141 - DelimCode: DelimCode2;
    Production {
        lhs: 44,
        production: &[ParseType::N(48)],
    },
    // 142 - DelimCode: DelimCode1;
    Production {
        lhs: 44,
        production: &[ParseType::N(45)],
    },
    // 143 - DelimCode1: DelimCodeStart1 DelimCode1List /* Vec */ DelimCodeEnd1;
    Production {
        lhs: 45,
        production: &[ParseType::N(54), ParseType::N(46), ParseType::N(57)],
    },
    // 144 - DelimCode1List: DelimCode1ListGroup DelimCode1List;
    Production {
        lhs: 46,
        production: &[ParseType::N(46), ParseType::N(47)],
    },
    // 145 - DelimCode1ListGroup: NoBacktick;
    Production {
        lhs: 47,
        production: &[ParseType::N(109)],
    },
    // 146 - DelimCode1ListGroup: BacktickDelim;
    Production {
        lhs: 47,
        production: &[ParseType::N(15)],
    },
    // 147 - DelimCode1List: ;
    Production {
        lhs: 46,
        production: &[],
    },
    // 148 - DelimCode2: DelimCodeStart2 DelimCode2List /* Vec */ DelimCodeEnd2;
    Production {
        lhs: 48,
        production: &[ParseType::N(55), ParseType::N(49), ParseType::N(58)],
    },
    // 149 - DelimCode2List: DelimCode2ListGroup DelimCode2List;
    Production {
        lhs: 49,
        production: &[ParseType::N(49), ParseType::N(50)],
    },
    // 150 - DelimCode2ListGroup: NoBacktick;
    Production {
        lhs: 50,
        production: &[ParseType::N(109)],
    },
    // 151 - DelimCode2ListGroup: BacktickDelim;
    Production {
        lhs: 50,
        production: &[ParseType::N(15)],
    },
    // 152 - DelimCode2List: ;
    Production {
        lhs: 49,
        production: &[],
    },
    // 153 - DelimCode3: DelimCodeStart3 DelimCode3List /* Vec */ DelimCodeEnd3;
    Production {
        lhs: 51,
        production: &[ParseType::N(56), ParseType::N(52), ParseType::N(59)],
    },
    // 154 - DelimCode3List: DelimCode3ListGroup DelimCode3List;
    Production {
        lhs: 52,
        production: &[ParseType::N(52), ParseType::N(53)],
    },
    // 155 - DelimCode3ListGroup: NoBacktick;
    Production {
        lhs: 53,
        production: &[ParseType::N(109)],
    },
    // 156 - DelimCode3ListGroup: BacktickDelim;
    Production {
        lhs: 53,
        production: &[ParseType::N(15)],
    },
    // 157 - DelimCode3List: ;
    Production {
        lhs: 52,
        production: &[],
    },
    // 158 - CodeBlock: CodeBlock3;
    Production {
        lhs: 21,
        production: &[ParseType::N(22)],
    },
    // 159 - CodeBlock: CodeBlock4;
    Production {
        lhs: 21,
        production: &[ParseType::N(25)],
    },
    // 160 - CodeBlock: CodeBlock5;
    Production {
        lhs: 21,
        production: &[ParseType::N(28)],
    },
    // 161 - CodeBlock: CodeBlock6;
    Production {
        lhs: 21,
        production: &[ParseType::N(31)],
    },
    // 162 - CodeBlock3: CodeBlockStart3 CodeBlock3List /* Vec */ CodeBlockEnd3;
    Production {
        lhs: 22,
        production: &[ParseType::N(34), ParseType::N(23), ParseType::N(38)],
    },
    // 163 - CodeBlock3List: CodeBlock3ListGroup CodeBlock3List;
    Production {
        lhs: 23,
        production: &[ParseType::N(23), ParseType::N(24)],
    },
    // 164 - CodeBlock3ListGroup: NoBacktick;
    Production {
        lhs: 24,
        production: &[ParseType::N(109)],
    },
    // 165 - CodeBlock3ListGroup: Backtick2;
    Production {
        lhs: 24,
        production: &[ParseType::N(11)],
    },
    // 166 - CodeBlock3List: ;
    Production {
        lhs: 23,
        production: &[],
    },
    // 167 - CodeBlock4: CodeBlockStart4 CodeBlock4List /* Vec */ CodeBlockEnd4;
    Production {
        lhs: 25,
        production: &[ParseType::N(35), ParseType::N(26), ParseType::N(39)],
    },
    // 168 - CodeBlock4List: CodeBlock4ListGroup CodeBlock4List;
    Production {
        lhs: 26,
        production: &[ParseType::N(26), ParseType::N(27)],
    },
    // 169 - CodeBlock4ListGroup: NoBacktick;
    Production {
        lhs: 27,
        production: &[ParseType::N(109)],
    },
    // 170 - CodeBlock4ListGroup: Backtick3;
    Production {
        lhs: 27,
        production: &[ParseType::N(12)],
    },
    // 171 - CodeBlock4List: ;
    Production {
        lhs: 26,
        production: &[],
    },
    // 172 - CodeBlock5: CodeBlockStart5 CodeBlock5List /* Vec */ CodeBlockEnd5;
    Production {
        lhs: 28,
        production: &[ParseType::N(36), ParseType::N(29), ParseType::N(40)],
    },
    // 173 - CodeBlock5List: CodeBlock5ListGroup CodeBlock5List;
    Production {
        lhs: 29,
        production: &[ParseType::N(29), ParseType::N(30)],
    },
    // 174 - CodeBlock5ListGroup: NoBacktick;
    Production {
        lhs: 30,
        production: &[ParseType::N(109)],
    },
    // 175 - CodeBlock5ListGroup: Backtick4;
    Production {
        lhs: 30,
        production: &[ParseType::N(13)],
    },
    // 176 - CodeBlock5List: ;
    Production {
        lhs: 29,
        production: &[],
    },
    // 177 - CodeBlock6: CodeBlockStart6 CodeBlock6List /* Vec */ CodeBlockEnd6;
    Production {
        lhs: 31,
        production: &[ParseType::N(37), ParseType::N(32), ParseType::N(41)],
    },
    // 178 - CodeBlock6List: CodeBlock6ListGroup CodeBlock6List;
    Production {
        lhs: 32,
        production: &[ParseType::N(32), ParseType::N(33)],
    },
    // 179 - CodeBlock6ListGroup: NoBacktick;
    Production {
        lhs: 33,
        production: &[ParseType::N(109)],
    },
    // 180 - CodeBlock6ListGroup: Backtick5;
    Production {
        lhs: 33,
        production: &[ParseType::N(14)],
    },
    // 181 - CodeBlock6List: ;
    Production {
        lhs: 32,
        production: &[],
    },
    // 182 - LitStr3Start: "<<<'";
    Production {
        lhs: 106,
        production: &[ParseType::T(19)],
    },
    // 183 - LitStr2Start: "<<'";
    Production {
        lhs: 101,
        production: &[ParseType::T(20)],
    },
    // 184 - LitStr1Start: "<'";
    Production {
        lhs: 96,
        production: &[ParseType::T(21)],
    },
    // 185 - DelimCodeStart3: /[a-zA-Z0-9-_]*<<<`/;
    Production {
        lhs: 59,
        production: &[ParseType::T(22)],
    },
    // 186 - DelimCodeStart2: /[a-zA-Z0-9-_]*<<`/;
    Production {
        lhs: 58,
        production: &[ParseType::T(23)],
    },
    // 187 - DelimCodeStart1: /[a-zA-Z0-9-_]*<`/;
    Production {
        lhs: 57,
        production: &[ParseType::T(24)],
    },
    // 188 - CodeBlockStart3: /`{3}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 38,
        production: &[ParseType::T(25)],
    },
    // 189 - CodeBlockStart4: /`{4}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 39,
        production: &[ParseType::T(26)],
    },
    // 190 - CodeBlockStart5: /`{5}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 40,
        production: &[ParseType::T(27)],
    },
    // 191 - CodeBlockStart6: /`{6}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 41,
        production: &[ParseType::T(28)],
    },
    // 192 - CodeBlockEnd3: /`{3}/;
    Production {
        lhs: 34,
        production: &[ParseType::T(29)],
    },
    // 193 - Backtick2: /`{1,2}/;
    Production {
        lhs: 11,
        production: &[ParseType::T(30)],
    },
    // 194 - CodeBlockEnd4: /`{4}/;
    Production {
        lhs: 35,
        production: &[ParseType::T(31)],
    },
    // 195 - Backtick3: /`{1,3}/;
    Production {
        lhs: 12,
        production: &[ParseType::T(32)],
    },
    // 196 - CodeBlockEnd5: /`{5}/;
    Production {
        lhs: 36,
        production: &[ParseType::T(33)],
    },
    // 197 - Backtick4: /`{1,4}/;
    Production {
        lhs: 13,
        production: &[ParseType::T(34)],
    },
    // 198 - CodeBlockEnd6: /`{6}/;
    Production {
        lhs: 37,
        production: &[ParseType::T(35)],
    },
    // 199 - Backtick5: /`{1,5}/;
    Production {
        lhs: 14,
        production: &[ParseType::T(36)],
    },
    // 200 - NoBacktick: /[^`]+/;
    Production {
        lhs: 109,
        production: &[ParseType::T(37)],
    },
    // 201 - LitStr3End: "'>>>";
    Production {
        lhs: 103,
        production: &[ParseType::T(38)],
    },
    // 202 - LitStr2End: "'>>";
    Production {
        lhs: 98,
        production: &[ParseType::T(39)],
    },
    // 203 - LitStr1End: "'>";
    Production {
        lhs: 93,
        production: &[ParseType::T(40)],
    },
    // 204 - SQuote: "'";
    Production {
        lhs: 119,
        production: &[ParseType::T(41)],
    },
    // 205 - NoSQuote: /[^']+/;
    Production {
        lhs: 110,
        production: &[ParseType::T(42)],
    },
    // 206 - DelimCodeEnd3: '`>>>';
    Production {
        lhs: 56,
        production: &[ParseType::T(43)],
    },
    // 207 - DelimCodeEnd2: '`>>';
    Production {
        lhs: 55,
        production: &[ParseType::T(44)],
    },
    // 208 - DelimCodeEnd1: '`>';
    Production {
        lhs: 54,
        production: &[ParseType::T(45)],
    },
    // 209 - BacktickDelim: '`';
    Production {
        lhs: 15,
        production: &[ParseType::T(46)],
    },
    // 210 - GrammarNewline: /\r\n|\r|\n/;
    Production {
        lhs: 70,
        production: &[ParseType::T(47)],
    },
    // 211 - Ws: /[\s--\r\n]+/;
    Production {
        lhs: 144,
        production: &[ParseType::T(48)],
    },
    // 212 - At: '@';
    Production {
        lhs: 10,
        production: &[ParseType::T(49)],
    },
    // 213 - Ext: '$';
    Production {
        lhs: 66,
        production: &[ParseType::T(50)],
    },
    // 214 - Dot: '.';
    Production {
        lhs: 60,
        production: &[ParseType::T(51)],
    },
    // 215 - Begin: '{';
    Production {
        lhs: 16,
        production: &[ParseType::T(52)],
    },
    // 216 - End: '}';
    Production {
        lhs: 61,
        production: &[ParseType::T(53)],
    },
    // 217 - ArrayBegin: '[';
    Production {
        lhs: 1,
        production: &[ParseType::T(54)],
    },
    // 218 - ArrayEnd: ']';
    Production {
        lhs: 6,
        production: &[ParseType::T(55)],
    },
    // 219 - LParen: '(';
    Production {
        lhs: 90,
        production: &[ParseType::T(56)],
    },
    // 220 - RParen: ')';
    Production {
        lhs: 118,
        production: &[ParseType::T(57)],
    },
    // 221 - Bind: '=';
    Production {
        lhs: 17,
        production: &[ParseType::T(58)],
    },
    // 222 - Comma: ',';
    Production {
        lhs: 42,
        production: &[ParseType::T(59)],
    },
    // 223 - Continue: '\';
    Production {
        lhs: 43,
        production: &[ParseType::T(60)],
    },
    // 224 - TextStart: ":";
    Production {
        lhs: 133,
        production: &[ParseType::T(61)],
    },
    // 225 - Ident: /[\p{XID_Start}_][\p{XID_Continue}-]*/;
    Production {
        lhs: 72,
        production: &[ParseType::T(62)],
    },
];

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut Grammar<'t>,
) -> Result<ParseTree, ParolError>
where
    T: AsRef<Path>,
{
    use parol_runtime::{
        parser::{parse_tree_type::SynTree, parser_types::SynTreeFlavor},
        syntree::Builder,
    };
    let mut builder = Builder::<SynTree, SynTreeFlavor>::new_with();
    parse_into(input, &mut builder, file_name, user_actions)?;
    Ok(builder.build()?)
}
#[allow(dead_code)]
pub fn parse_into<'t, T: TreeConstruct<'t>>(
    input: &'t str,
    tree_builder: &mut T,
    file_name: impl AsRef<Path>,
    user_actions: &mut Grammar<'t>,
) -> Result<(), ParolError>
where
    ParolError: From<T::Error>,
{
    use grammar_scanner::GrammarScanner;
    let mut llk_parser = LLKParser::new(
        62,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    let scanner = GrammarScanner::new();
    // Initialize wrapper
    let mut user_actions = GrammarAuto::new(user_actions);
    llk_parser.parse_into(
        tree_builder,
        TokenStream::new(
            input,
            file_name,
            scanner.scanner_impl.clone(),
            &GrammarScanner::match_function,
            MAX_K,
        )
        .unwrap(),
        &mut user_actions,
    )
}
