// ---------------------------------------------------------
// This file was generated by parol.
// It is not intended for manual editing and changes will be
// lost after next build.
// ---------------------------------------------------------

use parol_runtime::{
    ParolError, ParseTree, TokenStream,
    parser::{
        LLKParser, LookaheadDFA, ParseType, Production, Trans, parse_tree_type::TreeConstruct,
    },
};
use scnr2::scanner;
use std::path::Path;

use crate::grammar::Grammar;
use crate::grammar_trait::GrammarAuto;

pub const TERMINAL_NAMES: &[&str; 50] = &[
    /*  0 */ "EndOfInput",
    /*  1 */ "Newline",
    /*  2 */ "Whitespace",
    /*  3 */ "LineComment",
    /*  4 */ "BlockComment",
    /*  5 */ "Hash",
    /*  6 */ "MapBind",
    /*  7 */ "Float",
    /*  8 */ "Integer",
    /*  9 */ "True",
    /* 10 */ "False",
    /* 11 */ "Null",
    /* 12 */ "Hole",
    /* 13 */ "Str",
    /* 14 */ "Text",
    /* 15 */ "InlineCode1",
    /* 16 */ "InlineCodeStart2",
    /* 17 */ "CodeBlockStart3",
    /* 18 */ "CodeBlockStart4",
    /* 19 */ "CodeBlockStart5",
    /* 20 */ "CodeBlockStart6",
    /* 21 */ "CodeBlockEnd3",
    /* 22 */ "Backtick2",
    /* 23 */ "CodeBlockEnd4",
    /* 24 */ "Backtick3",
    /* 25 */ "CodeBlockEnd5",
    /* 26 */ "Backtick4",
    /* 27 */ "CodeBlockEnd6",
    /* 28 */ "Backtick5",
    /* 29 */ "InlineCodeEnd2",
    /* 30 */ "Backtick1",
    /* 31 */ "NoBacktick",
    /* 32 */ "NoBacktickInline",
    /* 33 */ "GrammarNewline",
    /* 34 */ "Ws",
    /* 35 */ "At",
    /* 36 */ "Ext",
    /* 37 */ "Dot",
    /* 38 */ "Begin",
    /* 39 */ "End",
    /* 40 */ "ArrayBegin",
    /* 41 */ "ArrayEnd",
    /* 42 */ "LParen",
    /* 43 */ "RParen",
    /* 44 */ "Bind",
    /* 45 */ "Comma",
    /* 46 */ "Continue",
    /* 47 */ "TextStart",
    /* 48 */ "Ident",
    /* 49 */ "Error",
];

scanner! {
    GrammarScanner {
        mode INITIAL {
            token r"\r\n|\r|\n" => 1; // "Newline"
            token r"[\s--\r\n]+" => 2; // "Whitespace"
            token r"//.*(\r\n|\r|\n)?" => 3; // "LineComment"
            token r"/\*/?([^/]|[^*]/)*\*/" => 4; // "BlockComment"
            token r"\#" => 5; // "Hash"
            token r"=>" => 6; // "MapBind"
            token r"[-+]?(\d+\.\d*|\d*\.\d+)([eE][-+]?\d+)?|[-+]?\d+[eE][-+]?\d+|[-+]?[Ii]nf|[Nn]a[Nn]" => 7; // "Float"
            token r"\d[\d_]*" => 8; // "Integer"
            token r"true" => 9; // "True"
            token r"false" => 10; // "False"
            token r"null" => 11; // "Null"
            token r"!" => 12; // "Hole"
            token r#""([^"]|\\")*""# => 13; // "Str"
            token r"[a-zA-Z0-9-_]*`[^`\r\n]*`" => 15; // "InlineCode1"
            token r"[a-zA-Z0-9-_]*``" => 16; // "InlineCodeStart2"
            token r"`{3}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 17; // "CodeBlockStart3"
            token r"`{4}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 18; // "CodeBlockStart4"
            token r"`{5}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 19; // "CodeBlockStart5"
            token r"`{6}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)" => 20; // "CodeBlockStart6"
            token r"@" => 35; // "At"
            token r"\$" => 36; // "Ext"
            token r"\." => 37; // "Dot"
            token r"\{" => 38; // "Begin"
            token r"\}" => 39; // "End"
            token r"\[" => 40; // "ArrayBegin"
            token r"\]" => 41; // "ArrayEnd"
            token r"\(" => 42; // "LParen"
            token r"\)" => 43; // "RParen"
            token r"=" => 44; // "Bind"
            token r"," => 45; // "Comma"
            token r"\\\\" => 46; // "Continue"
            token r":" => 47; // "TextStart"
            token r"[\p{XID_Start}_][\p{XID_Continue}-]*" => 48; // "Ident"
            token r"." => 49; // "Error"
            on 16 enter InInlineCode2;
            on 17 enter InCodeBlock3;
            on 18 enter InCodeBlock4;
            on 19 enter InCodeBlock5;
            on 20 enter InCodeBlock6;
            on 47 enter Text;
        }
        mode Text {
            token r"[^\r\n]*" => 14; // "Text"
            token r"\r\n|\r|\n" => 33; // "GrammarNewline"
            token r"[\s--\r\n]+" => 34; // "Ws"
            token r"." => 49; // "Error"
            on 14 enter INITIAL;
        }
        mode InInlineCode2 {
            token r"``" => 29; // "InlineCodeEnd2"
            token r"`" => 30; // "Backtick1"
            token r"[^`\r\n]+" => 32; // "NoBacktickInline"
            token r"." => 49; // "Error"
            on 29 enter INITIAL;
        }
        mode InCodeBlock3 {
            token r"`{3}" => 21; // "CodeBlockEnd3"
            token r"`{1,2}" => 22; // "Backtick2"
            token r"[^`]+" => 31; // "NoBacktick"
            token r"." => 49; // "Error"
            on 21 enter INITIAL;
        }
        mode InCodeBlock4 {
            token r"`{4}" => 23; // "CodeBlockEnd4"
            token r"`{1,3}" => 24; // "Backtick3"
            token r"[^`]+" => 31; // "NoBacktick"
            token r"." => 49; // "Error"
            on 23 enter INITIAL;
        }
        mode InCodeBlock5 {
            token r"`{5}" => 25; // "CodeBlockEnd5"
            token r"`{1,4}" => 26; // "Backtick4"
            token r"[^`]+" => 31; // "NoBacktick"
            token r"." => 49; // "Error"
            on 25 enter INITIAL;
        }
        mode InCodeBlock6 {
            token r"`{6}" => 27; // "CodeBlockEnd6"
            token r"`{1,5}" => 28; // "Backtick5"
            token r"[^`]+" => 31; // "NoBacktick"
            token r"." => 49; // "Error"
            on 27 enter INITIAL;
        }
    }
}

const MAX_K: usize = 1;

pub const NON_TERMINALS: &[&str; 114] = &[
    /*   0 */ "Array",
    /*   1 */ "ArrayBegin",
    /*   2 */ "ArrayElements",
    /*   3 */ "ArrayElementsOpt",
    /*   4 */ "ArrayElementsTail",
    /*   5 */ "ArrayElementsTailOpt",
    /*   6 */ "ArrayEnd",
    /*   7 */ "ArrayMarker",
    /*   8 */ "ArrayMarkerOpt",
    /*   9 */ "ArrayOpt",
    /*  10 */ "At",
    /*  11 */ "Backtick1",
    /*  12 */ "Backtick2",
    /*  13 */ "Backtick3",
    /*  14 */ "Backtick4",
    /*  15 */ "Backtick5",
    /*  16 */ "Begin",
    /*  17 */ "Bind",
    /*  18 */ "Binding",
    /*  19 */ "BindingRhs",
    /*  20 */ "Boolean",
    /*  21 */ "CodeBlock",
    /*  22 */ "CodeBlock3",
    /*  23 */ "CodeBlock3List",
    /*  24 */ "CodeBlock3ListGroup",
    /*  25 */ "CodeBlock4",
    /*  26 */ "CodeBlock4List",
    /*  27 */ "CodeBlock4ListGroup",
    /*  28 */ "CodeBlock5",
    /*  29 */ "CodeBlock5List",
    /*  30 */ "CodeBlock5ListGroup",
    /*  31 */ "CodeBlock6",
    /*  32 */ "CodeBlock6List",
    /*  33 */ "CodeBlock6ListGroup",
    /*  34 */ "CodeBlockEnd3",
    /*  35 */ "CodeBlockEnd4",
    /*  36 */ "CodeBlockEnd5",
    /*  37 */ "CodeBlockEnd6",
    /*  38 */ "CodeBlockStart3",
    /*  39 */ "CodeBlockStart4",
    /*  40 */ "CodeBlockStart5",
    /*  41 */ "CodeBlockStart6",
    /*  42 */ "Comma",
    /*  43 */ "Continue",
    /*  44 */ "Dot",
    /*  45 */ "End",
    /*  46 */ "Eure",
    /*  47 */ "EureList",
    /*  48 */ "EureList0",
    /*  49 */ "EureOpt",
    /*  50 */ "Ext",
    /*  51 */ "ExtensionNameSpace",
    /*  52 */ "False",
    /*  53 */ "Float",
    /*  54 */ "GrammarNewline",
    /*  55 */ "Hole",
    /*  56 */ "Ident",
    /*  57 */ "InlineCode",
    /*  58 */ "InlineCode1",
    /*  59 */ "InlineCode2",
    /*  60 */ "InlineCode2List",
    /*  61 */ "InlineCode2ListGroup",
    /*  62 */ "InlineCodeEnd2",
    /*  63 */ "InlineCodeStart2",
    /*  64 */ "Integer",
    /*  65 */ "Key",
    /*  66 */ "KeyBase",
    /*  67 */ "KeyIdent",
    /*  68 */ "KeyOpt",
    /*  69 */ "KeyTuple",
    /*  70 */ "KeyTupleElements",
    /*  71 */ "KeyTupleElementsOpt",
    /*  72 */ "KeyTupleElementsTail",
    /*  73 */ "KeyTupleElementsTailOpt",
    /*  74 */ "KeyTupleOpt",
    /*  75 */ "KeyValue",
    /*  76 */ "Keys",
    /*  77 */ "KeysList",
    /*  78 */ "LParen",
    /*  79 */ "MapBind",
    /*  80 */ "NoBacktick",
    /*  81 */ "NoBacktickInline",
    /*  82 */ "Null",
    /*  83 */ "Object",
    /*  84 */ "ObjectList",
    /*  85 */ "ObjectOpt",
    /*  86 */ "ObjectOpt0",
    /*  87 */ "ObjectOpt1",
    /*  88 */ "Path",
    /*  89 */ "RParen",
    /*  90 */ "Section",
    /*  91 */ "SectionBinding",
    /*  92 */ "SectionBody",
    /*  93 */ "SectionBodyList",
    /*  94 */ "SectionBodyOpt",
    /*  95 */ "Str",
    /*  96 */ "Strings",
    /*  97 */ "StringsList",
    /*  98 */ "Text",
    /*  99 */ "TextBinding",
    /* 100 */ "TextBindingOpt",
    /* 101 */ "TextBindingOpt0",
    /* 102 */ "TextStart",
    /* 103 */ "True",
    /* 104 */ "Tuple",
    /* 105 */ "TupleElements",
    /* 106 */ "TupleElementsOpt",
    /* 107 */ "TupleElementsTail",
    /* 108 */ "TupleElementsTailOpt",
    /* 109 */ "TupleIndex",
    /* 110 */ "TupleOpt",
    /* 111 */ "Value",
    /* 112 */ "ValueBinding",
    /* 113 */ "Ws",
];

pub const LOOKAHEAD_AUTOMATA: &[LookaheadDFA; 114] = &[
    /* 0 - "Array" */
    LookaheadDFA {
        prod0: 81,
        transitions: &[],
        k: 0,
    },
    /* 1 - "ArrayBegin" */
    LookaheadDFA {
        prod0: 169,
        transitions: &[],
        k: 0,
    },
    /* 2 - "ArrayElements" */
    LookaheadDFA {
        prod0: 84,
        transitions: &[],
        k: 0,
    },
    /* 3 - "ArrayElementsOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 41, 2, 86), Trans(0, 45, 1, 85)],
        k: 1,
    },
    /* 4 - "ArrayElementsTail" */
    LookaheadDFA {
        prod0: 87,
        transitions: &[],
        k: 0,
    },
    /* 5 - "ArrayElementsTailOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 88),
            Trans(0, 8, 1, 88),
            Trans(0, 9, 1, 88),
            Trans(0, 10, 1, 88),
            Trans(0, 11, 1, 88),
            Trans(0, 12, 1, 88),
            Trans(0, 13, 1, 88),
            Trans(0, 15, 1, 88),
            Trans(0, 16, 1, 88),
            Trans(0, 17, 1, 88),
            Trans(0, 18, 1, 88),
            Trans(0, 19, 1, 88),
            Trans(0, 20, 1, 88),
            Trans(0, 37, 1, 88),
            Trans(0, 38, 1, 88),
            Trans(0, 40, 1, 88),
            Trans(0, 41, 2, 89),
            Trans(0, 42, 1, 88),
        ],
        k: 1,
    },
    /* 6 - "ArrayEnd" */
    LookaheadDFA {
        prod0: 170,
        transitions: &[],
        k: 0,
    },
    /* 7 - "ArrayMarker" */
    LookaheadDFA {
        prod0: 31,
        transitions: &[],
        k: 0,
    },
    /* 8 - "ArrayMarkerOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 8, 1, 32), Trans(0, 41, 2, 33)],
        k: 1,
    },
    /* 9 - "ArrayOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 82),
            Trans(0, 8, 1, 82),
            Trans(0, 9, 1, 82),
            Trans(0, 10, 1, 82),
            Trans(0, 11, 1, 82),
            Trans(0, 12, 1, 82),
            Trans(0, 13, 1, 82),
            Trans(0, 15, 1, 82),
            Trans(0, 16, 1, 82),
            Trans(0, 17, 1, 82),
            Trans(0, 18, 1, 82),
            Trans(0, 19, 1, 82),
            Trans(0, 20, 1, 82),
            Trans(0, 37, 1, 82),
            Trans(0, 38, 1, 82),
            Trans(0, 40, 1, 82),
            Trans(0, 41, 2, 83),
            Trans(0, 42, 1, 82),
        ],
        k: 1,
    },
    /* 10 - "At" */
    LookaheadDFA {
        prod0: 164,
        transitions: &[],
        k: 0,
    },
    /* 11 - "Backtick1" */
    LookaheadDFA {
        prod0: 159,
        transitions: &[],
        k: 0,
    },
    /* 12 - "Backtick2" */
    LookaheadDFA {
        prod0: 151,
        transitions: &[],
        k: 0,
    },
    /* 13 - "Backtick3" */
    LookaheadDFA {
        prod0: 153,
        transitions: &[],
        k: 0,
    },
    /* 14 - "Backtick4" */
    LookaheadDFA {
        prod0: 155,
        transitions: &[],
        k: 0,
    },
    /* 15 - "Backtick5" */
    LookaheadDFA {
        prod0: 157,
        transitions: &[],
        k: 0,
    },
    /* 16 - "Begin" */
    LookaheadDFA {
        prod0: 167,
        transitions: &[],
        k: 0,
    },
    /* 17 - "Bind" */
    LookaheadDFA {
        prod0: 173,
        transitions: &[],
        k: 0,
    },
    /* 18 - "Binding" */
    LookaheadDFA {
        prod0: 7,
        transitions: &[],
        k: 0,
    },
    /* 19 - "BindingRhs" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 38, 2, 9), Trans(0, 44, 1, 8), Trans(0, 47, 3, 10)],
        k: 1,
    },
    /* 20 - "Boolean" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 9, 1, 101), Trans(0, 10, 2, 102)],
        k: 1,
    },
    /* 21 - "CodeBlock" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 17, 1, 121),
            Trans(0, 18, 2, 122),
            Trans(0, 19, 3, 123),
            Trans(0, 20, 4, 124),
        ],
        k: 1,
    },
    /* 22 - "CodeBlock3" */
    LookaheadDFA {
        prod0: 125,
        transitions: &[],
        k: 0,
    },
    /* 23 - "CodeBlock3List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 21, 2, 129),
            Trans(0, 22, 1, 126),
            Trans(0, 31, 1, 126),
        ],
        k: 1,
    },
    /* 24 - "CodeBlock3ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 22, 2, 128), Trans(0, 31, 1, 127)],
        k: 1,
    },
    /* 25 - "CodeBlock4" */
    LookaheadDFA {
        prod0: 130,
        transitions: &[],
        k: 0,
    },
    /* 26 - "CodeBlock4List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 23, 2, 134),
            Trans(0, 24, 1, 131),
            Trans(0, 31, 1, 131),
        ],
        k: 1,
    },
    /* 27 - "CodeBlock4ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 24, 2, 133), Trans(0, 31, 1, 132)],
        k: 1,
    },
    /* 28 - "CodeBlock5" */
    LookaheadDFA {
        prod0: 135,
        transitions: &[],
        k: 0,
    },
    /* 29 - "CodeBlock5List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 25, 2, 139),
            Trans(0, 26, 1, 136),
            Trans(0, 31, 1, 136),
        ],
        k: 1,
    },
    /* 30 - "CodeBlock5ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 26, 2, 138), Trans(0, 31, 1, 137)],
        k: 1,
    },
    /* 31 - "CodeBlock6" */
    LookaheadDFA {
        prod0: 140,
        transitions: &[],
        k: 0,
    },
    /* 32 - "CodeBlock6List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 27, 2, 144),
            Trans(0, 28, 1, 141),
            Trans(0, 31, 1, 141),
        ],
        k: 1,
    },
    /* 33 - "CodeBlock6ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 28, 2, 143), Trans(0, 31, 1, 142)],
        k: 1,
    },
    /* 34 - "CodeBlockEnd3" */
    LookaheadDFA {
        prod0: 150,
        transitions: &[],
        k: 0,
    },
    /* 35 - "CodeBlockEnd4" */
    LookaheadDFA {
        prod0: 152,
        transitions: &[],
        k: 0,
    },
    /* 36 - "CodeBlockEnd5" */
    LookaheadDFA {
        prod0: 154,
        transitions: &[],
        k: 0,
    },
    /* 37 - "CodeBlockEnd6" */
    LookaheadDFA {
        prod0: 156,
        transitions: &[],
        k: 0,
    },
    /* 38 - "CodeBlockStart3" */
    LookaheadDFA {
        prod0: 146,
        transitions: &[],
        k: 0,
    },
    /* 39 - "CodeBlockStart4" */
    LookaheadDFA {
        prod0: 147,
        transitions: &[],
        k: 0,
    },
    /* 40 - "CodeBlockStart5" */
    LookaheadDFA {
        prod0: 148,
        transitions: &[],
        k: 0,
    },
    /* 41 - "CodeBlockStart6" */
    LookaheadDFA {
        prod0: 149,
        transitions: &[],
        k: 0,
    },
    /* 42 - "Comma" */
    LookaheadDFA {
        prod0: 174,
        transitions: &[],
        k: 0,
    },
    /* 43 - "Continue" */
    LookaheadDFA {
        prod0: 175,
        transitions: &[],
        k: 0,
    },
    /* 44 - "Dot" */
    LookaheadDFA {
        prod0: 166,
        transitions: &[],
        k: 0,
    },
    /* 45 - "End" */
    LookaheadDFA {
        prod0: 168,
        transitions: &[],
        k: 0,
    },
    /* 46 - "Eure" */
    LookaheadDFA {
        prod0: 0,
        transitions: &[],
        k: 0,
    },
    /* 47 - "EureList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 4),
            Trans(0, 5, 1, 3),
            Trans(0, 8, 1, 3),
            Trans(0, 9, 1, 3),
            Trans(0, 10, 1, 3),
            Trans(0, 11, 1, 3),
            Trans(0, 13, 1, 3),
            Trans(0, 35, 2, 4),
            Trans(0, 36, 1, 3),
            Trans(0, 39, 2, 4),
            Trans(0, 42, 1, 3),
            Trans(0, 48, 1, 3),
        ],
        k: 1,
    },
    /* 48 - "EureList0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 0, 2, 2), Trans(0, 35, 1, 1), Trans(0, 39, 2, 2)],
        k: 1,
    },
    /* 49 - "EureOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 6),
            Trans(0, 5, 2, 6),
            Trans(0, 8, 2, 6),
            Trans(0, 9, 2, 6),
            Trans(0, 10, 2, 6),
            Trans(0, 11, 2, 6),
            Trans(0, 13, 2, 6),
            Trans(0, 35, 2, 6),
            Trans(0, 36, 2, 6),
            Trans(0, 39, 2, 6),
            Trans(0, 42, 2, 6),
            Trans(0, 44, 1, 5),
            Trans(0, 48, 2, 6),
        ],
        k: 1,
    },
    /* 50 - "Ext" */
    LookaheadDFA {
        prod0: 165,
        transitions: &[],
        k: 0,
    },
    /* 51 - "ExtensionNameSpace" */
    LookaheadDFA {
        prod0: 41,
        transitions: &[],
        k: 0,
    },
    /* 52 - "False" */
    LookaheadDFA {
        prod0: 104,
        transitions: &[],
        k: 0,
    },
    /* 53 - "Float" */
    LookaheadDFA {
        prod0: 99,
        transitions: &[],
        k: 0,
    },
    /* 54 - "GrammarNewline" */
    LookaheadDFA {
        prod0: 162,
        transitions: &[],
        k: 0,
    },
    /* 55 - "Hole" */
    LookaheadDFA {
        prod0: 106,
        transitions: &[],
        k: 0,
    },
    /* 56 - "Ident" */
    LookaheadDFA {
        prod0: 177,
        transitions: &[],
        k: 0,
    },
    /* 57 - "InlineCode" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 15, 2, 114), Trans(0, 16, 1, 113)],
        k: 1,
    },
    /* 58 - "InlineCode1" */
    LookaheadDFA {
        prod0: 115,
        transitions: &[],
        k: 0,
    },
    /* 59 - "InlineCode2" */
    LookaheadDFA {
        prod0: 116,
        transitions: &[],
        k: 0,
    },
    /* 60 - "InlineCode2List" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 29, 2, 120),
            Trans(0, 30, 1, 117),
            Trans(0, 32, 1, 117),
        ],
        k: 1,
    },
    /* 61 - "InlineCode2ListGroup" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 30, 2, 119), Trans(0, 32, 1, 118)],
        k: 1,
    },
    /* 62 - "InlineCodeEnd2" */
    LookaheadDFA {
        prod0: 158,
        transitions: &[],
        k: 0,
    },
    /* 63 - "InlineCodeStart2" */
    LookaheadDFA {
        prod0: 145,
        transitions: &[],
        k: 0,
    },
    /* 64 - "Integer" */
    LookaheadDFA {
        prod0: 100,
        transitions: &[],
        k: 0,
    },
    /* 65 - "Key" */
    LookaheadDFA {
        prod0: 28,
        transitions: &[],
        k: 0,
    },
    /* 66 - "KeyBase" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 6, 39),
            Trans(0, 8, 4, 37),
            Trans(0, 9, 1, 34),
            Trans(0, 10, 1, 34),
            Trans(0, 11, 1, 34),
            Trans(0, 13, 3, 36),
            Trans(0, 36, 2, 35),
            Trans(0, 42, 5, 38),
            Trans(0, 48, 1, 34),
        ],
        k: 1,
    },
    /* 67 - "KeyIdent" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 9, 2, 56),
            Trans(0, 10, 3, 57),
            Trans(0, 11, 4, 58),
            Trans(0, 48, 1, 55),
        ],
        k: 1,
    },
    /* 68 - "KeyOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 30),
            Trans(0, 5, 2, 30),
            Trans(0, 6, 2, 30),
            Trans(0, 8, 2, 30),
            Trans(0, 9, 2, 30),
            Trans(0, 10, 2, 30),
            Trans(0, 11, 2, 30),
            Trans(0, 13, 2, 30),
            Trans(0, 35, 2, 30),
            Trans(0, 36, 2, 30),
            Trans(0, 37, 2, 30),
            Trans(0, 38, 2, 30),
            Trans(0, 39, 2, 30),
            Trans(0, 40, 1, 29),
            Trans(0, 41, 2, 30),
            Trans(0, 42, 2, 30),
            Trans(0, 43, 2, 30),
            Trans(0, 44, 2, 30),
            Trans(0, 45, 2, 30),
            Trans(0, 47, 2, 30),
            Trans(0, 48, 2, 30),
        ],
        k: 1,
    },
    /* 69 - "KeyTuple" */
    LookaheadDFA {
        prod0: 42,
        transitions: &[],
        k: 0,
    },
    /* 70 - "KeyTupleElements" */
    LookaheadDFA {
        prod0: 45,
        transitions: &[],
        k: 0,
    },
    /* 71 - "KeyTupleElementsOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 43, 2, 47), Trans(0, 45, 1, 46)],
        k: 1,
    },
    /* 72 - "KeyTupleElementsTail" */
    LookaheadDFA {
        prod0: 48,
        transitions: &[],
        k: 0,
    },
    /* 73 - "KeyTupleElementsTailOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 8, 1, 49),
            Trans(0, 9, 1, 49),
            Trans(0, 10, 1, 49),
            Trans(0, 13, 1, 49),
            Trans(0, 42, 1, 49),
            Trans(0, 43, 2, 50),
        ],
        k: 1,
    },
    /* 74 - "KeyTupleOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 8, 1, 43),
            Trans(0, 9, 1, 43),
            Trans(0, 10, 1, 43),
            Trans(0, 13, 1, 43),
            Trans(0, 42, 1, 43),
            Trans(0, 43, 2, 44),
        ],
        k: 1,
    },
    /* 75 - "KeyValue" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 8, 1, 51),
            Trans(0, 9, 2, 52),
            Trans(0, 10, 2, 52),
            Trans(0, 13, 3, 53),
            Trans(0, 42, 4, 54),
        ],
        k: 1,
    },
    /* 76 - "Keys" */
    LookaheadDFA {
        prod0: 25,
        transitions: &[],
        k: 0,
    },
    /* 77 - "KeysList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 27),
            Trans(0, 5, 2, 27),
            Trans(0, 6, 2, 27),
            Trans(0, 8, 2, 27),
            Trans(0, 9, 2, 27),
            Trans(0, 10, 2, 27),
            Trans(0, 11, 2, 27),
            Trans(0, 13, 2, 27),
            Trans(0, 35, 2, 27),
            Trans(0, 36, 2, 27),
            Trans(0, 37, 1, 26),
            Trans(0, 38, 2, 27),
            Trans(0, 39, 2, 27),
            Trans(0, 41, 2, 27),
            Trans(0, 42, 2, 27),
            Trans(0, 43, 2, 27),
            Trans(0, 44, 2, 27),
            Trans(0, 45, 2, 27),
            Trans(0, 47, 2, 27),
            Trans(0, 48, 2, 27),
        ],
        k: 1,
    },
    /* 78 - "LParen" */
    LookaheadDFA {
        prod0: 171,
        transitions: &[],
        k: 0,
    },
    /* 79 - "MapBind" */
    LookaheadDFA {
        prod0: 80,
        transitions: &[],
        k: 0,
    },
    /* 80 - "NoBacktick" */
    LookaheadDFA {
        prod0: 160,
        transitions: &[],
        k: 0,
    },
    /* 81 - "NoBacktickInline" */
    LookaheadDFA {
        prod0: 161,
        transitions: &[],
        k: 0,
    },
    /* 82 - "Null" */
    LookaheadDFA {
        prod0: 105,
        transitions: &[],
        k: 0,
    },
    /* 83 - "Object" */
    LookaheadDFA {
        prod0: 71,
        transitions: &[],
        k: 0,
    },
    /* 84 - "ObjectList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 1, 72),
            Trans(0, 8, 1, 72),
            Trans(0, 9, 1, 72),
            Trans(0, 10, 1, 72),
            Trans(0, 11, 1, 72),
            Trans(0, 13, 1, 72),
            Trans(0, 36, 1, 72),
            Trans(0, 39, 2, 73),
            Trans(0, 42, 1, 72),
            Trans(0, 48, 1, 72),
        ],
        k: 1,
    },
    /* 85 - "ObjectOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 79),
            Trans(0, 8, 2, 79),
            Trans(0, 9, 2, 79),
            Trans(0, 10, 2, 79),
            Trans(0, 11, 2, 79),
            Trans(0, 13, 2, 79),
            Trans(0, 36, 2, 79),
            Trans(0, 39, 2, 79),
            Trans(0, 42, 2, 79),
            Trans(0, 44, 1, 76),
            Trans(0, 48, 2, 79),
        ],
        k: 1,
    },
    /* 86 - "ObjectOpt0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 75),
            Trans(0, 8, 2, 75),
            Trans(0, 9, 2, 75),
            Trans(0, 10, 2, 75),
            Trans(0, 11, 2, 75),
            Trans(0, 13, 2, 75),
            Trans(0, 36, 2, 75),
            Trans(0, 39, 2, 75),
            Trans(0, 42, 2, 75),
            Trans(0, 45, 1, 74),
            Trans(0, 48, 2, 75),
        ],
        k: 1,
    },
    /* 87 - "ObjectOpt1" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 5, 2, 78),
            Trans(0, 8, 2, 78),
            Trans(0, 9, 2, 78),
            Trans(0, 10, 2, 78),
            Trans(0, 11, 2, 78),
            Trans(0, 13, 2, 78),
            Trans(0, 36, 2, 78),
            Trans(0, 39, 2, 78),
            Trans(0, 42, 2, 78),
            Trans(0, 45, 1, 77),
            Trans(0, 48, 2, 78),
        ],
        k: 1,
    },
    /* 88 - "Path" */
    LookaheadDFA {
        prod0: 107,
        transitions: &[],
        k: 0,
    },
    /* 89 - "RParen" */
    LookaheadDFA {
        prod0: 172,
        transitions: &[],
        k: 0,
    },
    /* 90 - "Section" */
    LookaheadDFA {
        prod0: 18,
        transitions: &[],
        k: 0,
    },
    /* 91 - "SectionBinding" */
    LookaheadDFA {
        prod0: 12,
        transitions: &[],
        k: 0,
    },
    /* 92 - "SectionBody" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 1, 19),
            Trans(0, 5, 1, 19),
            Trans(0, 8, 1, 19),
            Trans(0, 9, 1, 19),
            Trans(0, 10, 1, 19),
            Trans(0, 11, 1, 19),
            Trans(0, 13, 1, 19),
            Trans(0, 35, 1, 19),
            Trans(0, 36, 1, 19),
            Trans(0, 38, 2, 22),
            Trans(0, 39, 1, 19),
            Trans(0, 42, 1, 19),
            Trans(0, 44, 1, 19),
            Trans(0, 48, 1, 19),
        ],
        k: 1,
    },
    /* 93 - "SectionBodyList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 21),
            Trans(0, 5, 1, 20),
            Trans(0, 8, 1, 20),
            Trans(0, 9, 1, 20),
            Trans(0, 10, 1, 20),
            Trans(0, 11, 1, 20),
            Trans(0, 13, 1, 20),
            Trans(0, 35, 2, 21),
            Trans(0, 36, 1, 20),
            Trans(0, 39, 2, 21),
            Trans(0, 42, 1, 20),
            Trans(0, 48, 1, 20),
        ],
        k: 1,
    },
    /* 94 - "SectionBodyOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 24),
            Trans(0, 5, 2, 24),
            Trans(0, 8, 2, 24),
            Trans(0, 9, 2, 24),
            Trans(0, 10, 2, 24),
            Trans(0, 11, 2, 24),
            Trans(0, 13, 2, 24),
            Trans(0, 35, 2, 24),
            Trans(0, 36, 2, 24),
            Trans(0, 39, 2, 24),
            Trans(0, 42, 2, 24),
            Trans(0, 44, 1, 23),
            Trans(0, 48, 2, 24),
        ],
        k: 1,
    },
    /* 95 - "Str" */
    LookaheadDFA {
        prod0: 111,
        transitions: &[],
        k: 0,
    },
    /* 96 - "Strings" */
    LookaheadDFA {
        prod0: 108,
        transitions: &[],
        k: 0,
    },
    /* 97 - "StringsList" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 110),
            Trans(0, 5, 2, 110),
            Trans(0, 8, 2, 110),
            Trans(0, 9, 2, 110),
            Trans(0, 10, 2, 110),
            Trans(0, 11, 2, 110),
            Trans(0, 13, 2, 110),
            Trans(0, 35, 2, 110),
            Trans(0, 36, 2, 110),
            Trans(0, 39, 2, 110),
            Trans(0, 41, 2, 110),
            Trans(0, 42, 2, 110),
            Trans(0, 43, 2, 110),
            Trans(0, 45, 2, 110),
            Trans(0, 46, 1, 109),
            Trans(0, 48, 2, 110),
        ],
        k: 1,
    },
    /* 98 - "Text" */
    LookaheadDFA {
        prod0: 112,
        transitions: &[],
        k: 0,
    },
    /* 99 - "TextBinding" */
    LookaheadDFA {
        prod0: 13,
        transitions: &[],
        k: 0,
    },
    /* 100 - "TextBindingOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 14, 2, 17), Trans(0, 34, 1, 16)],
        k: 1,
    },
    /* 101 - "TextBindingOpt0" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 0, 2, 15),
            Trans(0, 5, 2, 15),
            Trans(0, 8, 2, 15),
            Trans(0, 9, 2, 15),
            Trans(0, 10, 2, 15),
            Trans(0, 11, 2, 15),
            Trans(0, 13, 2, 15),
            Trans(0, 33, 1, 14),
            Trans(0, 35, 2, 15),
            Trans(0, 36, 2, 15),
            Trans(0, 39, 2, 15),
            Trans(0, 42, 2, 15),
            Trans(0, 48, 2, 15),
        ],
        k: 1,
    },
    /* 102 - "TextStart" */
    LookaheadDFA {
        prod0: 176,
        transitions: &[],
        k: 0,
    },
    /* 103 - "True" */
    LookaheadDFA {
        prod0: 103,
        transitions: &[],
        k: 0,
    },
    /* 104 - "Tuple" */
    LookaheadDFA {
        prod0: 90,
        transitions: &[],
        k: 0,
    },
    /* 105 - "TupleElements" */
    LookaheadDFA {
        prod0: 93,
        transitions: &[],
        k: 0,
    },
    /* 106 - "TupleElementsOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[Trans(0, 43, 2, 95), Trans(0, 45, 1, 94)],
        k: 1,
    },
    /* 107 - "TupleElementsTail" */
    LookaheadDFA {
        prod0: 96,
        transitions: &[],
        k: 0,
    },
    /* 108 - "TupleElementsTailOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 97),
            Trans(0, 8, 1, 97),
            Trans(0, 9, 1, 97),
            Trans(0, 10, 1, 97),
            Trans(0, 11, 1, 97),
            Trans(0, 12, 1, 97),
            Trans(0, 13, 1, 97),
            Trans(0, 15, 1, 97),
            Trans(0, 16, 1, 97),
            Trans(0, 17, 1, 97),
            Trans(0, 18, 1, 97),
            Trans(0, 19, 1, 97),
            Trans(0, 20, 1, 97),
            Trans(0, 37, 1, 97),
            Trans(0, 38, 1, 97),
            Trans(0, 40, 1, 97),
            Trans(0, 42, 1, 97),
            Trans(0, 43, 2, 98),
        ],
        k: 1,
    },
    /* 109 - "TupleIndex" */
    LookaheadDFA {
        prod0: 40,
        transitions: &[],
        k: 0,
    },
    /* 110 - "TupleOpt" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 1, 91),
            Trans(0, 8, 1, 91),
            Trans(0, 9, 1, 91),
            Trans(0, 10, 1, 91),
            Trans(0, 11, 1, 91),
            Trans(0, 12, 1, 91),
            Trans(0, 13, 1, 91),
            Trans(0, 15, 1, 91),
            Trans(0, 16, 1, 91),
            Trans(0, 17, 1, 91),
            Trans(0, 18, 1, 91),
            Trans(0, 19, 1, 91),
            Trans(0, 20, 1, 91),
            Trans(0, 37, 1, 91),
            Trans(0, 38, 1, 91),
            Trans(0, 40, 1, 91),
            Trans(0, 42, 1, 91),
            Trans(0, 43, 2, 92),
        ],
        k: 1,
    },
    /* 111 - "Value" */
    LookaheadDFA {
        prod0: -1,
        transitions: &[
            Trans(0, 7, 4, 62),
            Trans(0, 8, 5, 63),
            Trans(0, 9, 6, 64),
            Trans(0, 10, 6, 64),
            Trans(0, 11, 7, 65),
            Trans(0, 12, 9, 67),
            Trans(0, 13, 8, 66),
            Trans(0, 15, 11, 69),
            Trans(0, 16, 11, 69),
            Trans(0, 17, 10, 68),
            Trans(0, 18, 10, 68),
            Trans(0, 19, 10, 68),
            Trans(0, 20, 10, 68),
            Trans(0, 37, 12, 70),
            Trans(0, 38, 1, 59),
            Trans(0, 40, 2, 60),
            Trans(0, 42, 3, 61),
        ],
        k: 1,
    },
    /* 112 - "ValueBinding" */
    LookaheadDFA {
        prod0: 11,
        transitions: &[],
        k: 0,
    },
    /* 113 - "Ws" */
    LookaheadDFA {
        prod0: 163,
        transitions: &[],
        k: 0,
    },
];

pub const PRODUCTIONS: &[Production; 178] = &[
    // 0 - Eure: EureOpt /* Option */ EureList /* Vec */ EureList0 /* Vec */;
    Production {
        lhs: 46,
        production: &[ParseType::N(48), ParseType::N(47), ParseType::N(49)],
    },
    // 1 - EureList0: Section EureList0;
    Production {
        lhs: 48,
        production: &[ParseType::N(48), ParseType::N(90)],
    },
    // 2 - EureList0: ;
    Production {
        lhs: 48,
        production: &[],
    },
    // 3 - EureList: Binding EureList;
    Production {
        lhs: 47,
        production: &[ParseType::N(47), ParseType::N(18)],
    },
    // 4 - EureList: ;
    Production {
        lhs: 47,
        production: &[],
    },
    // 5 - EureOpt: ValueBinding;
    Production {
        lhs: 49,
        production: &[ParseType::N(112)],
    },
    // 6 - EureOpt: ;
    Production {
        lhs: 49,
        production: &[],
    },
    // 7 - Binding: Keys BindingRhs;
    Production {
        lhs: 18,
        production: &[ParseType::N(19), ParseType::N(76)],
    },
    // 8 - BindingRhs: ValueBinding;
    Production {
        lhs: 19,
        production: &[ParseType::N(112)],
    },
    // 9 - BindingRhs: SectionBinding;
    Production {
        lhs: 19,
        production: &[ParseType::N(91)],
    },
    // 10 - BindingRhs: TextBinding;
    Production {
        lhs: 19,
        production: &[ParseType::N(99)],
    },
    // 11 - ValueBinding: Bind Value;
    Production {
        lhs: 112,
        production: &[ParseType::N(111), ParseType::N(17)],
    },
    // 12 - SectionBinding: Begin Eure End;
    Production {
        lhs: 91,
        production: &[ParseType::N(45), ParseType::N(46), ParseType::N(16)],
    },
    // 13 - TextBinding: TextStart TextBindingOpt /* Option */ Text TextBindingOpt0 /* Option */;
    Production {
        lhs: 99,
        production: &[
            ParseType::N(101),
            ParseType::N(98),
            ParseType::N(100),
            ParseType::N(102),
        ],
    },
    // 14 - TextBindingOpt0: GrammarNewline;
    Production {
        lhs: 101,
        production: &[ParseType::N(54)],
    },
    // 15 - TextBindingOpt0: ;
    Production {
        lhs: 101,
        production: &[],
    },
    // 16 - TextBindingOpt: Ws^ /* Clipped */;
    Production {
        lhs: 100,
        production: &[ParseType::N(113)],
    },
    // 17 - TextBindingOpt: ;
    Production {
        lhs: 100,
        production: &[],
    },
    // 18 - Section: At Keys SectionBody;
    Production {
        lhs: 90,
        production: &[ParseType::N(92), ParseType::N(76), ParseType::N(10)],
    },
    // 19 - SectionBody: SectionBodyOpt /* Option */ SectionBodyList /* Vec */;
    Production {
        lhs: 92,
        production: &[ParseType::N(93), ParseType::N(94)],
    },
    // 20 - SectionBodyList: Binding SectionBodyList;
    Production {
        lhs: 93,
        production: &[ParseType::N(93), ParseType::N(18)],
    },
    // 21 - SectionBodyList: ;
    Production {
        lhs: 93,
        production: &[],
    },
    // 22 - SectionBody: Begin Eure End;
    Production {
        lhs: 92,
        production: &[ParseType::N(45), ParseType::N(46), ParseType::N(16)],
    },
    // 23 - SectionBodyOpt: ValueBinding;
    Production {
        lhs: 94,
        production: &[ParseType::N(112)],
    },
    // 24 - SectionBodyOpt: ;
    Production {
        lhs: 94,
        production: &[],
    },
    // 25 - Keys: Key KeysList /* Vec */;
    Production {
        lhs: 76,
        production: &[ParseType::N(77), ParseType::N(65)],
    },
    // 26 - KeysList: Dot Key KeysList;
    Production {
        lhs: 77,
        production: &[ParseType::N(77), ParseType::N(65), ParseType::N(44)],
    },
    // 27 - KeysList: ;
    Production {
        lhs: 77,
        production: &[],
    },
    // 28 - Key: KeyBase KeyOpt /* Option */;
    Production {
        lhs: 65,
        production: &[ParseType::N(68), ParseType::N(66)],
    },
    // 29 - KeyOpt: ArrayMarker;
    Production {
        lhs: 68,
        production: &[ParseType::N(7)],
    },
    // 30 - KeyOpt: ;
    Production {
        lhs: 68,
        production: &[],
    },
    // 31 - ArrayMarker: ArrayBegin ArrayMarkerOpt /* Option */ ArrayEnd;
    Production {
        lhs: 7,
        production: &[ParseType::N(6), ParseType::N(8), ParseType::N(1)],
    },
    // 32 - ArrayMarkerOpt: Integer;
    Production {
        lhs: 8,
        production: &[ParseType::N(64)],
    },
    // 33 - ArrayMarkerOpt: ;
    Production {
        lhs: 8,
        production: &[],
    },
    // 34 - KeyBase: KeyIdent;
    Production {
        lhs: 66,
        production: &[ParseType::N(67)],
    },
    // 35 - KeyBase: ExtensionNameSpace;
    Production {
        lhs: 66,
        production: &[ParseType::N(51)],
    },
    // 36 - KeyBase: Str;
    Production {
        lhs: 66,
        production: &[ParseType::N(95)],
    },
    // 37 - KeyBase: Integer;
    Production {
        lhs: 66,
        production: &[ParseType::N(64)],
    },
    // 38 - KeyBase: KeyTuple;
    Production {
        lhs: 66,
        production: &[ParseType::N(69)],
    },
    // 39 - KeyBase: TupleIndex;
    Production {
        lhs: 66,
        production: &[ParseType::N(109)],
    },
    // 40 - TupleIndex: '#' Integer;
    Production {
        lhs: 109,
        production: &[ParseType::N(64), ParseType::T(5)],
    },
    // 41 - ExtensionNameSpace: Ext KeyIdent;
    Production {
        lhs: 51,
        production: &[ParseType::N(67), ParseType::N(50)],
    },
    // 42 - KeyTuple: LParen KeyTupleOpt /* Option */ RParen;
    Production {
        lhs: 69,
        production: &[ParseType::N(89), ParseType::N(74), ParseType::N(78)],
    },
    // 43 - KeyTupleOpt: KeyTupleElements;
    Production {
        lhs: 74,
        production: &[ParseType::N(70)],
    },
    // 44 - KeyTupleOpt: ;
    Production {
        lhs: 74,
        production: &[],
    },
    // 45 - KeyTupleElements: KeyValue KeyTupleElementsOpt /* Option */;
    Production {
        lhs: 70,
        production: &[ParseType::N(71), ParseType::N(75)],
    },
    // 46 - KeyTupleElementsOpt: KeyTupleElementsTail;
    Production {
        lhs: 71,
        production: &[ParseType::N(72)],
    },
    // 47 - KeyTupleElementsOpt: ;
    Production {
        lhs: 71,
        production: &[],
    },
    // 48 - KeyTupleElementsTail: Comma KeyTupleElementsTailOpt /* Option */;
    Production {
        lhs: 72,
        production: &[ParseType::N(73), ParseType::N(42)],
    },
    // 49 - KeyTupleElementsTailOpt: KeyTupleElements;
    Production {
        lhs: 73,
        production: &[ParseType::N(70)],
    },
    // 50 - KeyTupleElementsTailOpt: ;
    Production {
        lhs: 73,
        production: &[],
    },
    // 51 - KeyValue: Integer;
    Production {
        lhs: 75,
        production: &[ParseType::N(64)],
    },
    // 52 - KeyValue: Boolean;
    Production {
        lhs: 75,
        production: &[ParseType::N(20)],
    },
    // 53 - KeyValue: Str;
    Production {
        lhs: 75,
        production: &[ParseType::N(95)],
    },
    // 54 - KeyValue: KeyTuple;
    Production {
        lhs: 75,
        production: &[ParseType::N(69)],
    },
    // 55 - KeyIdent: Ident;
    Production {
        lhs: 67,
        production: &[ParseType::N(56)],
    },
    // 56 - KeyIdent: True;
    Production {
        lhs: 67,
        production: &[ParseType::N(103)],
    },
    // 57 - KeyIdent: False;
    Production {
        lhs: 67,
        production: &[ParseType::N(52)],
    },
    // 58 - KeyIdent: Null;
    Production {
        lhs: 67,
        production: &[ParseType::N(82)],
    },
    // 59 - Value: Object;
    Production {
        lhs: 111,
        production: &[ParseType::N(83)],
    },
    // 60 - Value: Array;
    Production {
        lhs: 111,
        production: &[ParseType::N(0)],
    },
    // 61 - Value: Tuple;
    Production {
        lhs: 111,
        production: &[ParseType::N(104)],
    },
    // 62 - Value: Float;
    Production {
        lhs: 111,
        production: &[ParseType::N(53)],
    },
    // 63 - Value: Integer;
    Production {
        lhs: 111,
        production: &[ParseType::N(64)],
    },
    // 64 - Value: Boolean;
    Production {
        lhs: 111,
        production: &[ParseType::N(20)],
    },
    // 65 - Value: Null;
    Production {
        lhs: 111,
        production: &[ParseType::N(82)],
    },
    // 66 - Value: Strings;
    Production {
        lhs: 111,
        production: &[ParseType::N(96)],
    },
    // 67 - Value: Hole;
    Production {
        lhs: 111,
        production: &[ParseType::N(55)],
    },
    // 68 - Value: CodeBlock;
    Production {
        lhs: 111,
        production: &[ParseType::N(21)],
    },
    // 69 - Value: InlineCode;
    Production {
        lhs: 111,
        production: &[ParseType::N(57)],
    },
    // 70 - Value: Path;
    Production {
        lhs: 111,
        production: &[ParseType::N(88)],
    },
    // 71 - Object: Begin ObjectOpt /* Option */ ObjectList /* Vec */ End;
    Production {
        lhs: 83,
        production: &[
            ParseType::N(45),
            ParseType::N(84),
            ParseType::N(85),
            ParseType::N(16),
        ],
    },
    // 72 - ObjectList: Keys MapBind Value ObjectOpt0 /* Option */ ObjectList;
    Production {
        lhs: 84,
        production: &[
            ParseType::N(84),
            ParseType::N(86),
            ParseType::N(111),
            ParseType::N(79),
            ParseType::N(76),
        ],
    },
    // 73 - ObjectList: ;
    Production {
        lhs: 84,
        production: &[],
    },
    // 74 - ObjectOpt0: Comma;
    Production {
        lhs: 86,
        production: &[ParseType::N(42)],
    },
    // 75 - ObjectOpt0: ;
    Production {
        lhs: 86,
        production: &[],
    },
    // 76 - ObjectOpt: ValueBinding ObjectOpt1 /* Option */;
    Production {
        lhs: 85,
        production: &[ParseType::N(87), ParseType::N(112)],
    },
    // 77 - ObjectOpt1: Comma;
    Production {
        lhs: 87,
        production: &[ParseType::N(42)],
    },
    // 78 - ObjectOpt1: ;
    Production {
        lhs: 87,
        production: &[],
    },
    // 79 - ObjectOpt: ;
    Production {
        lhs: 85,
        production: &[],
    },
    // 80 - MapBind: '=>';
    Production {
        lhs: 79,
        production: &[ParseType::T(6)],
    },
    // 81 - Array: ArrayBegin ArrayOpt /* Option */ ArrayEnd;
    Production {
        lhs: 0,
        production: &[ParseType::N(6), ParseType::N(9), ParseType::N(1)],
    },
    // 82 - ArrayOpt: ArrayElements;
    Production {
        lhs: 9,
        production: &[ParseType::N(2)],
    },
    // 83 - ArrayOpt: ;
    Production {
        lhs: 9,
        production: &[],
    },
    // 84 - ArrayElements: Value ArrayElementsOpt /* Option */;
    Production {
        lhs: 2,
        production: &[ParseType::N(3), ParseType::N(111)],
    },
    // 85 - ArrayElementsOpt: ArrayElementsTail;
    Production {
        lhs: 3,
        production: &[ParseType::N(4)],
    },
    // 86 - ArrayElementsOpt: ;
    Production {
        lhs: 3,
        production: &[],
    },
    // 87 - ArrayElementsTail: Comma ArrayElementsTailOpt /* Option */;
    Production {
        lhs: 4,
        production: &[ParseType::N(5), ParseType::N(42)],
    },
    // 88 - ArrayElementsTailOpt: ArrayElements;
    Production {
        lhs: 5,
        production: &[ParseType::N(2)],
    },
    // 89 - ArrayElementsTailOpt: ;
    Production {
        lhs: 5,
        production: &[],
    },
    // 90 - Tuple: LParen TupleOpt /* Option */ RParen;
    Production {
        lhs: 104,
        production: &[ParseType::N(89), ParseType::N(110), ParseType::N(78)],
    },
    // 91 - TupleOpt: TupleElements;
    Production {
        lhs: 110,
        production: &[ParseType::N(105)],
    },
    // 92 - TupleOpt: ;
    Production {
        lhs: 110,
        production: &[],
    },
    // 93 - TupleElements: Value TupleElementsOpt /* Option */;
    Production {
        lhs: 105,
        production: &[ParseType::N(106), ParseType::N(111)],
    },
    // 94 - TupleElementsOpt: TupleElementsTail;
    Production {
        lhs: 106,
        production: &[ParseType::N(107)],
    },
    // 95 - TupleElementsOpt: ;
    Production {
        lhs: 106,
        production: &[],
    },
    // 96 - TupleElementsTail: Comma TupleElementsTailOpt /* Option */;
    Production {
        lhs: 107,
        production: &[ParseType::N(108), ParseType::N(42)],
    },
    // 97 - TupleElementsTailOpt: TupleElements;
    Production {
        lhs: 108,
        production: &[ParseType::N(105)],
    },
    // 98 - TupleElementsTailOpt: ;
    Production {
        lhs: 108,
        production: &[],
    },
    // 99 - Float: /[-+]?(\d+\.\d*|\d*\.\d+)([eE][-+]?\d+)?|[-+]?\d+[eE][-+]?\d+|[-+]?[Ii]nf|[Nn]a[Nn]/;
    Production {
        lhs: 53,
        production: &[ParseType::T(7)],
    },
    // 100 - Integer: /\d[\d_]*/;
    Production {
        lhs: 64,
        production: &[ParseType::T(8)],
    },
    // 101 - Boolean: True;
    Production {
        lhs: 20,
        production: &[ParseType::N(103)],
    },
    // 102 - Boolean: False;
    Production {
        lhs: 20,
        production: &[ParseType::N(52)],
    },
    // 103 - True: 'true';
    Production {
        lhs: 103,
        production: &[ParseType::T(9)],
    },
    // 104 - False: 'false';
    Production {
        lhs: 52,
        production: &[ParseType::T(10)],
    },
    // 105 - Null: 'null';
    Production {
        lhs: 82,
        production: &[ParseType::T(11)],
    },
    // 106 - Hole: '!';
    Production {
        lhs: 55,
        production: &[ParseType::T(12)],
    },
    // 107 - Path: Dot Keys;
    Production {
        lhs: 88,
        production: &[ParseType::N(76), ParseType::N(44)],
    },
    // 108 - Strings: Str StringsList /* Vec */;
    Production {
        lhs: 96,
        production: &[ParseType::N(97), ParseType::N(95)],
    },
    // 109 - StringsList: Continue Str StringsList;
    Production {
        lhs: 97,
        production: &[ParseType::N(97), ParseType::N(95), ParseType::N(43)],
    },
    // 110 - StringsList: ;
    Production {
        lhs: 97,
        production: &[],
    },
    // 111 - Str: /"([^"]|\\")*"/;
    Production {
        lhs: 95,
        production: &[ParseType::T(13)],
    },
    // 112 - Text: /[^\r\n]*/;
    Production {
        lhs: 98,
        production: &[ParseType::T(14)],
    },
    // 113 - InlineCode: InlineCode2;
    Production {
        lhs: 57,
        production: &[ParseType::N(59)],
    },
    // 114 - InlineCode: InlineCode1;
    Production {
        lhs: 57,
        production: &[ParseType::N(58)],
    },
    // 115 - InlineCode1: /[a-zA-Z0-9-_]*`[^`\r\n]*`/;
    Production {
        lhs: 58,
        production: &[ParseType::T(15)],
    },
    // 116 - InlineCode2: InlineCodeStart2 InlineCode2List /* Vec */ InlineCodeEnd2;
    Production {
        lhs: 59,
        production: &[ParseType::N(62), ParseType::N(60), ParseType::N(63)],
    },
    // 117 - InlineCode2List: InlineCode2ListGroup InlineCode2List;
    Production {
        lhs: 60,
        production: &[ParseType::N(60), ParseType::N(61)],
    },
    // 118 - InlineCode2ListGroup: NoBacktickInline;
    Production {
        lhs: 61,
        production: &[ParseType::N(81)],
    },
    // 119 - InlineCode2ListGroup: Backtick1;
    Production {
        lhs: 61,
        production: &[ParseType::N(11)],
    },
    // 120 - InlineCode2List: ;
    Production {
        lhs: 60,
        production: &[],
    },
    // 121 - CodeBlock: CodeBlock3;
    Production {
        lhs: 21,
        production: &[ParseType::N(22)],
    },
    // 122 - CodeBlock: CodeBlock4;
    Production {
        lhs: 21,
        production: &[ParseType::N(25)],
    },
    // 123 - CodeBlock: CodeBlock5;
    Production {
        lhs: 21,
        production: &[ParseType::N(28)],
    },
    // 124 - CodeBlock: CodeBlock6;
    Production {
        lhs: 21,
        production: &[ParseType::N(31)],
    },
    // 125 - CodeBlock3: CodeBlockStart3 CodeBlock3List /* Vec */ CodeBlockEnd3;
    Production {
        lhs: 22,
        production: &[ParseType::N(34), ParseType::N(23), ParseType::N(38)],
    },
    // 126 - CodeBlock3List: CodeBlock3ListGroup CodeBlock3List;
    Production {
        lhs: 23,
        production: &[ParseType::N(23), ParseType::N(24)],
    },
    // 127 - CodeBlock3ListGroup: NoBacktick;
    Production {
        lhs: 24,
        production: &[ParseType::N(80)],
    },
    // 128 - CodeBlock3ListGroup: Backtick2;
    Production {
        lhs: 24,
        production: &[ParseType::N(12)],
    },
    // 129 - CodeBlock3List: ;
    Production {
        lhs: 23,
        production: &[],
    },
    // 130 - CodeBlock4: CodeBlockStart4 CodeBlock4List /* Vec */ CodeBlockEnd4;
    Production {
        lhs: 25,
        production: &[ParseType::N(35), ParseType::N(26), ParseType::N(39)],
    },
    // 131 - CodeBlock4List: CodeBlock4ListGroup CodeBlock4List;
    Production {
        lhs: 26,
        production: &[ParseType::N(26), ParseType::N(27)],
    },
    // 132 - CodeBlock4ListGroup: NoBacktick;
    Production {
        lhs: 27,
        production: &[ParseType::N(80)],
    },
    // 133 - CodeBlock4ListGroup: Backtick3;
    Production {
        lhs: 27,
        production: &[ParseType::N(13)],
    },
    // 134 - CodeBlock4List: ;
    Production {
        lhs: 26,
        production: &[],
    },
    // 135 - CodeBlock5: CodeBlockStart5 CodeBlock5List /* Vec */ CodeBlockEnd5;
    Production {
        lhs: 28,
        production: &[ParseType::N(36), ParseType::N(29), ParseType::N(40)],
    },
    // 136 - CodeBlock5List: CodeBlock5ListGroup CodeBlock5List;
    Production {
        lhs: 29,
        production: &[ParseType::N(29), ParseType::N(30)],
    },
    // 137 - CodeBlock5ListGroup: NoBacktick;
    Production {
        lhs: 30,
        production: &[ParseType::N(80)],
    },
    // 138 - CodeBlock5ListGroup: Backtick4;
    Production {
        lhs: 30,
        production: &[ParseType::N(14)],
    },
    // 139 - CodeBlock5List: ;
    Production {
        lhs: 29,
        production: &[],
    },
    // 140 - CodeBlock6: CodeBlockStart6 CodeBlock6List /* Vec */ CodeBlockEnd6;
    Production {
        lhs: 31,
        production: &[ParseType::N(37), ParseType::N(32), ParseType::N(41)],
    },
    // 141 - CodeBlock6List: CodeBlock6ListGroup CodeBlock6List;
    Production {
        lhs: 32,
        production: &[ParseType::N(32), ParseType::N(33)],
    },
    // 142 - CodeBlock6ListGroup: NoBacktick;
    Production {
        lhs: 33,
        production: &[ParseType::N(80)],
    },
    // 143 - CodeBlock6ListGroup: Backtick5;
    Production {
        lhs: 33,
        production: &[ParseType::N(15)],
    },
    // 144 - CodeBlock6List: ;
    Production {
        lhs: 32,
        production: &[],
    },
    // 145 - InlineCodeStart2: /[a-zA-Z0-9-_]*``/;
    Production {
        lhs: 63,
        production: &[ParseType::T(16)],
    },
    // 146 - CodeBlockStart3: /`{3}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 38,
        production: &[ParseType::T(17)],
    },
    // 147 - CodeBlockStart4: /`{4}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 39,
        production: &[ParseType::T(18)],
    },
    // 148 - CodeBlockStart5: /`{5}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 40,
        production: &[ParseType::T(19)],
    },
    // 149 - CodeBlockStart6: /`{6}[a-zA-Z0-9-_]*[\s--\r\n]*(\r\n|\r|\n)/;
    Production {
        lhs: 41,
        production: &[ParseType::T(20)],
    },
    // 150 - CodeBlockEnd3: /`{3}/;
    Production {
        lhs: 34,
        production: &[ParseType::T(21)],
    },
    // 151 - Backtick2: /`{1,2}/;
    Production {
        lhs: 12,
        production: &[ParseType::T(22)],
    },
    // 152 - CodeBlockEnd4: /`{4}/;
    Production {
        lhs: 35,
        production: &[ParseType::T(23)],
    },
    // 153 - Backtick3: /`{1,3}/;
    Production {
        lhs: 13,
        production: &[ParseType::T(24)],
    },
    // 154 - CodeBlockEnd5: /`{5}/;
    Production {
        lhs: 36,
        production: &[ParseType::T(25)],
    },
    // 155 - Backtick4: /`{1,4}/;
    Production {
        lhs: 14,
        production: &[ParseType::T(26)],
    },
    // 156 - CodeBlockEnd6: /`{6}/;
    Production {
        lhs: 37,
        production: &[ParseType::T(27)],
    },
    // 157 - Backtick5: /`{1,5}/;
    Production {
        lhs: 15,
        production: &[ParseType::T(28)],
    },
    // 158 - InlineCodeEnd2: '``';
    Production {
        lhs: 62,
        production: &[ParseType::T(29)],
    },
    // 159 - Backtick1: '`';
    Production {
        lhs: 11,
        production: &[ParseType::T(30)],
    },
    // 160 - NoBacktick: /[^`]+/;
    Production {
        lhs: 80,
        production: &[ParseType::T(31)],
    },
    // 161 - NoBacktickInline: /[^`\r\n]+/;
    Production {
        lhs: 81,
        production: &[ParseType::T(32)],
    },
    // 162 - GrammarNewline: /\r\n|\r|\n/;
    Production {
        lhs: 54,
        production: &[ParseType::T(33)],
    },
    // 163 - Ws: /[\s--\r\n]+/;
    Production {
        lhs: 113,
        production: &[ParseType::T(34)],
    },
    // 164 - At: '@';
    Production {
        lhs: 10,
        production: &[ParseType::T(35)],
    },
    // 165 - Ext: '$';
    Production {
        lhs: 50,
        production: &[ParseType::T(36)],
    },
    // 166 - Dot: '.';
    Production {
        lhs: 44,
        production: &[ParseType::T(37)],
    },
    // 167 - Begin: '{';
    Production {
        lhs: 16,
        production: &[ParseType::T(38)],
    },
    // 168 - End: '}';
    Production {
        lhs: 45,
        production: &[ParseType::T(39)],
    },
    // 169 - ArrayBegin: '[';
    Production {
        lhs: 1,
        production: &[ParseType::T(40)],
    },
    // 170 - ArrayEnd: ']';
    Production {
        lhs: 6,
        production: &[ParseType::T(41)],
    },
    // 171 - LParen: '(';
    Production {
        lhs: 78,
        production: &[ParseType::T(42)],
    },
    // 172 - RParen: ')';
    Production {
        lhs: 89,
        production: &[ParseType::T(43)],
    },
    // 173 - Bind: '=';
    Production {
        lhs: 17,
        production: &[ParseType::T(44)],
    },
    // 174 - Comma: ',';
    Production {
        lhs: 42,
        production: &[ParseType::T(45)],
    },
    // 175 - Continue: '\\';
    Production {
        lhs: 43,
        production: &[ParseType::T(46)],
    },
    // 176 - TextStart: ":";
    Production {
        lhs: 102,
        production: &[ParseType::T(47)],
    },
    // 177 - Ident: /[\p{XID_Start}_][\p{XID_Continue}-]*/;
    Production {
        lhs: 56,
        production: &[ParseType::T(48)],
    },
];

pub fn parse<'t, T>(
    input: &'t str,
    file_name: T,
    user_actions: &mut Grammar<'t>,
) -> Result<ParseTree, ParolError>
where
    T: AsRef<Path>,
{
    use parol_runtime::{
        parser::{parse_tree_type::SynTree, parser_types::SynTreeFlavor},
        syntree::Builder,
    };
    let mut builder = Builder::<SynTree, SynTreeFlavor>::new_with();
    parse_into(input, &mut builder, file_name, user_actions)?;
    Ok(builder.build()?)
}
#[allow(dead_code)]
pub fn parse_into<'t, T: TreeConstruct<'t>>(
    input: &'t str,
    tree_builder: &mut T,
    file_name: impl AsRef<Path>,
    user_actions: &mut Grammar<'t>,
) -> Result<(), ParolError>
where
    ParolError: From<T::Error>,
{
    use grammar_scanner::GrammarScanner;
    let mut llk_parser = LLKParser::new(
        46,
        LOOKAHEAD_AUTOMATA,
        PRODUCTIONS,
        TERMINAL_NAMES,
        NON_TERMINALS,
    );
    let scanner = GrammarScanner::new();
    // Initialize wrapper
    let mut user_actions = GrammarAuto::new(user_actions);
    llk_parser.parse_into(
        tree_builder,
        TokenStream::new(
            input,
            file_name,
            scanner.scanner_impl.clone(),
            &GrammarScanner::match_function,
            MAX_K,
        )
        .unwrap(),
        &mut user_actions,
    )
}
