id = "eure"
name = "Eure"
version = "0.2.0"
schema_version = 1
authors = ["Ryo Hirayama <ryo12redstone@gmail.com>"]
description = "Eure language support for Zed (language server, syntax highlighting, bracket matching, code outline)"
repository = "https://github.com/Hihaheho/eure"

[language_servers.eurels]
name = "Eure Language Server"
languages = ["Eure"]

[grammars.eure]
repository = "https://github.com/eure-lang/tree-sitter-eure"
commit = "e4ecb904ac254b7c38c349d4784a6c97c9473ebb"
