[package]
name = "swon-yaml"
version = "0.1.0"
edition = "2024"
description = "YAML conversion support for SWON format"
license = "MIT OR Apache-2.0"
homepage = "https://swon.dev"
repository = "https://github.com/Hihaheho/swon"
readme = "README.md"

[dependencies]
