[package]
name = "swon"
version = "0.1.0"
edition = "2024"
description = "SWON - SWan Object Notation core library"
license = "MIT OR Apache-2.0"
homepage = "https://swon.dev"
repository = "https://github.com/Hihaheho/swon"
readme = "README.md"

[dependencies]
