[package]
name = "swon-tree"
version = "0.1.0"
edition = "2024"

[dependencies]
swon-value = { workspace = true }

petgraph = { workspace = true }
thiserror = { workspace = true }
thisisplural = { workspace = true }
ahash = { workspace = true }
